import { hslToInt } from '../../../legacy/util/palette.ts'
import type { MapDef } from '../../../legacy/types/maps'

export default {
  emoji: '1fae7',
  name: '深海',
  desc: '大陆坡上一道海底峡谷的谷底，两三百米深，阳光只透下来一层幽蓝的微光，谷底看得清个大概。两侧是陡峭的岩壁，上游一头是塌下来的岩堆，下游一头是往下没进黑暗的陡坎，都过不去；谷底铺着软泥，散着大石头，躺着一副鲸骨，还有冒泡的冷泉。队伍从一艘停在谷底的潜艇里出来：潜艇只有一侧开着门，门口罩着一团空气，门上的灯照亮门前一片。离开门口只能憋着气：气不会自己回来，歇着也一点点往下掉，赶路掉得更快；绕回门口换口气，很快就补满。艇身挡人也挡子弹，敌人只能从开门的那一侧压过来。气见底了就呛水掉血。潜艇隔一阵自己开走：先猛地排出一大团气泡、关上门，浮起来从头顶开过去，换个地方停下，开走的那一阵哪里都换不了气；落点的地上先画出艇身和门口那一片。海里的东西用不着换气',
  kind: 'deep',
  stamina: { exertion: 0.35, regen: 1 },
  palette: {
    bgFrom: 'hsl(212 64% 22%)',
    bgTo: 'hsl(224 72% 6%)',
    map: hslToInt(214, 0.5, 0.22),
  },
  // 没有太阳：光来自头顶透下来的那层幽蓝、潜艇门上与艇首的灯和队员的头灯，迎着灯的一面泛白、背面沉进深蓝；没有接影子的光
  light: { sun: 0xdbeaff, shade: 0x35507e },
  decor: {
    emojis: ['1fae7'],
    sizeU: [0.3, 0.5],
    alpha: [0, 0],
    density: [0, 0],
  },
  foes: ['fishSchool', 'pearlClam', 'porcupineFish', 'conch', 'shark', 'seepBubble', 'abyssEye', 'doorCoral'],
  // 石缝里游出来、从岩堆上爬下来、从陡坎下面浮上来、从鲸骨底下钻出来、冷泉里冒出来、从头顶的黑暗里沉下来、从软泥里钻出来；蛇颈龙与深渊巨鲸从陡坎下面上来
  gates: {
    snapU: 3,
    fallback: 'rise',
    look: 'silt',
    boss: 'abyss',
    kinds: {
      crack: { name: '石缝', at: { kind: 'nooks', spacingU: 6, away: { mark: 'ends', minU: 3 } }, enter: 'walk', look: 'silt', weight: 3, perSec: 1.5, only: ['conch', 'shark', 'fishSchool', 'doorCoral', 'seepBubble'] },
      rubble: { name: '岩堆', at: { kind: 'mark' }, enter: 'climb', weight: 2, perSec: 1, only: ['conch', 'shark', 'doorCoral'] },
      abyss: { name: '陡坎下', at: { kind: 'mark' }, enter: 'climb', look: 'silt', weight: 3, perSec: 1.5, only: ['conch', 'seepBubble', 'porcupineFish', 'abyssEye', 'fishSchool', 'abyssWhale', 'shark', 'plesiosaur'] },
      bones: { name: '鲸骨', at: { kind: 'mark' }, enter: 'walk', look: 'silt', weight: 2, perSec: 1, only: ['seepBubble', 'doorCoral', 'porcupineFish', 'fishSchool', 'pearlClam', 'conch'] },
      seep: { name: '冷泉', at: { kind: 'mark' }, enter: 'rise', look: 'bubbles', weight: 1.5, perSec: 1, only: ['porcupineFish', 'seepBubble'] },
      above: { name: '头顶', at: { kind: 'ground' }, enter: 'drop', look: 'silt', weight: 1, only: ['porcupineFish', 'seepBubble', 'conch', 'abyssEye'] },
      ooze: { name: '软泥', at: { kind: 'ground' }, enter: 'rise', look: 'silt', weight: 1 },
    },
  },
  deep: {
    meterPerU: 0.5,
    sizeU: 36,
    areaU2: [520, 840],
    neckU: 0.4,
    floor: { reliefM: 0.18, waveU: 6, tiltM: 0.035 },
    walls: { insetU: [3.8, 6.5], bendU: 1.8, waveU: 9, heightM: [9, 14], slopeU: [2.2, 3.4] },
    rubble: { insetU: [3.2, 5.5], bendU: 1.4, waveU: 7, blockU: [0.5, 1.3], heightM: [3, 4.5], slopeU: 3 },
    lip: { insetU: [3, 5], bendU: 1.5, waveU: 8, dropM: 1.2 },
    boulders: { count: [6, 10], radiusU: [0.55, 1.5], heightM: [0.9, 2.6], clearU: 4.8, gapU: 2.2, wallShare: 0.4 },
    whale: { lengthM: [7, 9], clearU: 6.5, skullM: 0.85 },
    seeps: { count: [1, 2], radiusU: [1.1, 1.8], clearU: 5 },
    sub: {
      lengthU: 7,
      beamU: 2.5,
      heightM: 2.6,
      doorU: 2.6,
      cruiseM: 6,
      breath: 48,
      hold: 1.6,
      drownSec: 12,
      tickMs: 250,
      firstMs: 60000,
      intervalMs: 75000,
      jitterMs: 10000,
      warnMs: 5000,
      riseMs: 3000,
      settleMs: 3500,
      speedMs: 1.6,
      moveU: [7, 12],
      roomU: 0.5,
    },
  },
  bosses: ['plesiosaur', 'abyssWhale'],
} as const satisfies MapDef
