import type { EnemyDef } from '../src/types/enemies'

export const ZOMBIE: EnemyDef = {
  kind: 'zombie',
  locomotion: { kind: 'chase' },
  emoji: '1f9df',
  name: '僵尸',
  desc: '缓慢但成群，最基础的追击者',
  size: 1.35,
  radius: 0.5,
  hp: 60,
  speed: 1.375,
  damage: 8,
  xp: 3,
  coins: 2,
}

export const GHOST: EnemyDef = {
  kind: 'ghost',
  locomotion: { kind: 'chase' },
  emoji: '1f47b',
  name: '幽灵',
  phasesWalls: true,
  desc: '飘得很快的追击者，血薄，能穿墙直取队伍，死亡时治疗周围同伴',
  size: 1.2,
  radius: 0.45,
  hp: 25,
  speed: 2.875,
  damage: 5,
  xp: 2,
  coins: 2,
  onDeath: [{ kind: 'heal', range: 3, amount: 12, all: true }],
}

export const INVADER: EnemyDef = {
  kind: 'invader',
  locomotion: { kind: 'wander' },
  emoji: '1f47e',
  name: '外星怪',
  desc: '不追人，游荡途中朝前方吐慢速弹，死亡放一记冷枪',
  size: 1.25,
  radius: 0.48,
  hp: 40,
  speed: 0.9,
  damage: 6,
  xp: 4,
  coins: 3,
  abilities: [
    {
      kind: 'projectile',
      damage: 6,
      cooldownMs: 2800,
      knockback: 0,
      aim: 'move',
      lifeMs: 4500,
      projectile: { emoji: '1f534', size: 0.4, radius: 0.14, speed: 3, rotationOffsetDeg: 0 },
    },
  ],
  onDeath: [
    {
      kind: 'spawnProjectile',
      aim: 'nearest',
      damage: 8,
      lifeMs: 6000,
      projectile: { emoji: '1f6f8', size: 0.6, radius: 0.2, speed: 1.5, rotationOffsetDeg: 0 },
    },
  ],
}

export const BOAR: EnemyDef = {
  kind: 'boar',
  emoji: '1f417',
  name: '野猪',
  desc: '发现猎物后蓄力直线突刺，横向可躲，死亡留半透明尸壳诱骗火力',
  size: 1.4,
  radius: 0.52,
  hp: 80,
  speed: 1.1,
  damage: 10,
  xp: 5,
  coins: 3,
  locomotion: {
    kind: 'dash',
    trigger: { kind: 'detect', range: 4, cooldownMs: 1800 },
    length: { kind: 'dist', dist: 3.5 },
    windupMs: 550,
    dashSpeed: 8,
    idle: 'wander',
    aim: 'nearest',
    lockAt: 'windup',
  },
  onDeath: [{ kind: 'decoy', hp: 40, durationMs: 3000, alpha: 0.5 }],
}

export const SNAKE: EnemyDef = {
  kind: 'snake',
  emoji: '1f40d',
  name: '毒蛇',
  desc: '围着玩家维持定距，站定吐毒弹，太近才后退',
  size: 1.25,
  radius: 0.45,
  hp: 35,
  speed: 2.4,
  damage: 5,
  xp: 4,
  coins: 3,
  locomotion: { kind: 'standoff', detectRange: 8, standoffDist: 5 },
  abilities: [
    {
      kind: 'projectile',
      damage: 5,
      cooldownMs: 2600,
      knockback: 0,
      // 须大于 standoffDist
      range: 8,
      lifeMs: 4500,
      projectile: { emoji: '1f7e2', size: 0.4, radius: 0.14, speed: 3.2, rotationOffsetDeg: 0 },
    },
  ],
}

export const MUSHROOM: EnemyDef = {
  kind: 'mushroom',
  locomotion: { kind: 'chase' },
  emoji: '1f344',
  name: '毒蘑菇',
  desc: '死亡时在原地留下一片毒液',
  size: 1.25,
  radius: 0.46,
  hp: 50,
  speed: 1,
  damage: 6,
  xp: 4,
  coins: 3,
  onDeath: [
    {
      kind: 'ground',
      def: {
        radius: 1.6,
        durationMs: 3000,
        tickMs: 500,
        damage: 4,
        color: 0x7cb342,
        fillAlpha: 0.22,
        lineAlpha: 0.5,
        enterMs: 220,
      },
    },
  ],
}

export const RAT: EnemyDef = {
  kind: 'rat',
  locomotion: { kind: 'coinThief' },
  emoji: '1f400',
  name: '偷币鼠',
  desc: '专偷地上的金币，击杀可全额讨回并有利息',
  size: 1.05,
  radius: 0.4,
  hp: 30,
  speed: 3.2,
  damage: 3,
  xp: 3,
  coins: 2,
}

export const SLIME: EnemyDef = {
  kind: 'slime',
  locomotion: { kind: 'chase' },
  emoji: '1f40c',
  name: '黏黏怪',
  desc: '缓慢肉盾，蹭到的队员会被黏住，攻速大降数秒',
  size: 1.3,
  radius: 0.5,
  hp: 55,
  speed: 1.1,
  damage: 5,
  xp: 4,
  coins: 3,
  onContact: [{ kind: 'attackSlow', mul: 1.6, durationMs: 3000 }],
}

export const BLOBLING: EnemyDef = {
  kind: 'blobling',
  locomotion: { kind: 'chase' },
  emoji: '1fae7',
  name: '小泡泡',
  desc: '泡泡分裂出的迷你体，快而脆',
  size: 0.75,
  radius: 0.28,
  hp: 18,
  speed: 2.6,
  damage: 4,
  xp: 1,
  coins: 0,
}

export const BLOB: EnemyDef = {
  kind: 'blob',
  locomotion: { kind: 'chase' },
  emoji: '1fae7',
  name: '泡泡',
  desc: '被击破时分裂成两只小泡泡',
  size: 1.55,
  radius: 0.55,
  hp: 70,
  speed: 1.2,
  damage: 6,
  xp: 4,
  coins: 3,
  onDeath: [{ kind: 'split', into: BLOBLING, count: 2 }],
}

export const LARVA: EnemyDef = {
  kind: 'larva',
  locomotion: {
    kind: 'baseOrbit',
    orbitRadius: 2.5,
    aggroRange: 6,
    orphanSpeedMul: 1.7,
    orphanDamageMul: 2.5,
  },
  emoji: '1f99f',
  name: '小飞虫',
  desc: '绕着虫巢盘旋守卫，玩家逼近巢就扑击；巢被拆后暴走直扑玩家',
  size: 0.7,
  radius: 0.26,
  hp: 12,
  speed: 2.8,
  damage: 3,
  xp: 1,
  coins: 0,
}

export const HIVE: EnemyDef = {
  kind: 'hive',
  locomotion: { kind: 'static' },
  emoji: '1faba',
  name: '虫巢',
  desc: '原地不动的巢穴，每隔几秒吐出小飞虫，不拆掉就一直刷',
  size: 1.5,
  radius: 0.6,
  hp: 140,
  speed: 0,
  damage: 4,
  xp: 8,
  coins: 6,
  kbImmune: true,
  spawner: { into: LARVA, intervalMs: 4000, count: 2, maxAlive: 6, firstDelayMs: 2000 },
}

export const CREEPER: EnemyDef = {
  kind: 'creeper',
  emoji: '1f4a3',
  name: '自爆怪',
  desc: '径直扑向玩家，贴身后定身蓄力随即原地引爆，蓄力前击杀可拆弹',
  size: 1.3,
  radius: 0.5,
  hp: 55,
  speed: 1.6,
  damage: 6,
  xp: 6,
  coins: 4,
  locomotion: {
    kind: 'detonate',
    triggerRange: 2.6,
    windupMs: 800,
    blastRadius: 3.8,
    blastDamage: 32,
  },
}

export const ELF: EnemyDef = {
  kind: 'elf',
  locomotion: { kind: 'chase' },
  emoji: '1f9dd',
  name: '林祭司',
  desc: '林间祭司，每隔几秒群体治疗周围受伤的同伴——不先清它，怪潮就一直被奶回来',
  size: 1.3,
  radius: 0.5,
  hp: 65,
  speed: 1.3,
  damage: 5,
  xp: 5,
  coins: 4,
  abilities: [{ kind: 'heal', amount: 13, cooldownMs: 2600, range: 3.5, aoe: { ratio: 1 } }],
}

export const TURTLE: EnemyDef = {
  kind: 'turtle',
  locomotion: { kind: 'chase' },
  emoji: '1f422',
  name: '炮龟',
  desc: '缓慢的重甲龟，边逼近边朝队伍抛射一串硬壳弹，血厚、免疫击退',
  size: 1.5,
  radius: 0.6,
  hp: 130,
  speed: 0.8,
  damage: 8,
  xp: 7,
  coins: 5,
  kbImmune: true,
  abilities: [
    {
      kind: 'projectile',
      damage: 7,
      cooldownMs: 3000,
      knockback: 0,
      aim: 'nearest',
      firstDelayMs: 1500,
      lifeMs: 5000,
      volley: { count: 3, spreadDeg: 36 },
      projectile: { emoji: '1faa8', size: 0.4, radius: 0.15, speed: 2.6, rotationOffsetDeg: 0 },
    },
  ],
}

export const LOCUST: EnemyDef = {
  kind: 'locust',
  emoji: '1f997',
  name: '跳蝗',
  desc: '成群蝗虫一蹦一蹦地扑来，脆皮但高频跳突，专挤压走位空间',
  size: 0.9,
  radius: 0.35,
  hp: 20,
  speed: 1.0,
  damage: 4,
  xp: 2,
  coins: 1,
  locomotion: {
    kind: 'dash',
    trigger: { kind: 'timer', intervalMs: 1400, firstDelayMs: 600 },
    length: { kind: 'dist', dist: 2.2 },
    windupMs: 200,
    dashSpeed: 7,
    idle: 'chase',
    aim: 'nearest',
    lockAt: 'launch',
  },
}

export const GARGOYLE: EnemyDef = {
  kind: 'gargoyle',
  locomotion: { kind: 'chase' },
  emoji: '1f5ff',
  name: '石像鬼',
  desc: '沉重的石像守卫，血极厚、移速慢、免疫击退，硬生生压上来堵路吸火力',
  size: 1.6,
  radius: 0.62,
  hp: 200,
  speed: 0.85,
  damage: 12,
  xp: 8,
  coins: 6,
  kbImmune: true,
}

export const PUFFER: EnemyDef = {
  kind: 'puffer',
  emoji: '1f421',
  name: '毒河豚',
  desc: '鼓胀的毒河豚，贴身即鼓爆一团毒气冲击；被戳破则炸开一大片残留毒云，别在走位线上戳它',
  size: 1.3,
  radius: 0.5,
  hp: 45,
  speed: 1.2,
  damage: 5,
  xp: 5,
  coins: 4,
  locomotion: {
    kind: 'detonate',
    triggerRange: 2.0,
    windupMs: 700,
    blastRadius: 2.8,
    blastDamage: 22,
  },
  onDeath: [
    {
      kind: 'ground',
      def: {
        radius: 2.2,
        durationMs: 3200,
        tickMs: 500,
        damage: 5,
        color: 0x8bc34a,
        fillAlpha: 0.24,
        lineAlpha: 0.5,
        enterMs: 220,
      },
    },
  ],
}

const UFO: EnemyDef = {
  kind: 'ufo',
  emoji: '1f6f8',
  name: '飞碟',
  desc: '悬停的碟形来客，绕着队伍维持定距，站定俯射能量弹',
  size: 1.35,
  radius: 0.5,
  hp: 55,
  speed: 1.8,
  damage: 6,
  xp: 5,
  coins: 4,
  locomotion: { kind: 'standoff', detectRange: 9, standoffDist: 6 },
  abilities: [
    {
      kind: 'projectile',
      damage: 6,
      cooldownMs: 2400,
      knockback: 0,
      range: 9,
      lifeMs: 4500,
      projectile: { emoji: '1f4ab', size: 0.45, radius: 0.15, speed: 3.4, rotationOffsetDeg: 0 },
    },
  ],
}

const ALIEN: EnemyDef = {
  kind: 'alien',
  emoji: '1f47d',
  name: '小灰人',
  desc: '成群逼近的灰皮异星客，脆但快，贴身骚扰',
  size: 1.1,
  radius: 0.42,
  hp: 26,
  speed: 3.4,
  damage: 7,
  xp: 4,
  coins: 2,
  locomotion: { kind: 'chase' },
}

const COMET: EnemyDef = {
  kind: 'comet',
  emoji: '2604',
  name: '流星',
  desc: '拖着尾焰蓄势，锁定后直线疾冲，横向可躲',
  size: 1.3,
  radius: 0.5,
  hp: 30,
  speed: 1.4,
  damage: 12,
  xp: 5,
  coins: 3,
  locomotion: {
    kind: 'dash',
    windupMs: 240,
    dashSpeed: 8,
    trigger: { kind: 'detect', range: 5, cooldownMs: 1600 },
    length: { kind: 'dist', dist: 2.8 },
    idle: 'chase',
    aim: 'nearest',
    lockAt: 'launch',
    sfx: 'whoosh',
  },
}

export const ENEMY_DEFS: readonly EnemyDef[] = [
  ZOMBIE,
  GHOST,
  INVADER,
  BOAR,
  SNAKE,
  MUSHROOM,
  RAT,
  SLIME,
  BLOB,
  BLOBLING,
  HIVE,
  LARVA,
  CREEPER,
  ELF,
  TURTLE,
  LOCUST,
  GARGOYLE,
  PUFFER,
  UFO,
  ALIEN,
  COMET,
]

// ── Boss ──

const FOREST_BOSS: EnemyDef = {
  kind: 'treant',
  role: 'boss',
  emoji: '1f333',
  name: '树妖',
  desc: '黑森林头目：召唤毒菌蔓生战场，喷吐孢子扇幕，缓慢厚重，击退免疫',
  size: 3.4,
  radius: 1.1,
  hp: 6500,
  speed: 1.0,
  damage: 20,
  xp: 60,
  coins: 60,
  kbImmune: true,
  locomotion: { kind: 'chase' },
  spawner: { into: MUSHROOM, intervalMs: 5200, count: 2, maxAlive: 6, firstDelayMs: 3000 },
  abilities: [
    {
      kind: 'projectile',
      damage: 8,
      cooldownMs: 3200,
      knockback: 0,
      firstDelayMs: 2000,
      lifeMs: 6000,
      volley: { count: 7, spreadDeg: 160 },
      projectile: { emoji: '1f7e2', size: 0.42, radius: 0.15, speed: 2.4, rotationOffsetDeg: 0 },
    },
  ],
}

const DESERT_BOSS: EnemyDef = {
  kind: 'scorpion',
  role: 'boss',
  emoji: '1f982',
  name: '蝎王',
  desc: '荒漠头目：掘沙尾刺猛扑突袭，喷射毒液扇幕，击退免疫',
  size: 3.2,
  radius: 1.05,
  hp: 6000,
  speed: 1.5,
  damage: 22,
  xp: 60,
  coins: 60,
  kbImmune: true,
  locomotion: {
    kind: 'dash',
    trigger: { kind: 'timer', intervalMs: 5000, firstDelayMs: 3500 },
    length: { kind: 'time', durationMs: 500 },
    windupMs: 650,
    dashSpeed: 11,
    idle: 'chase',
    aim: 'teamCenter',
    lockAt: 'launch',
    sfx: 'whoosh',
  },
  abilities: [
    {
      kind: 'projectile',
      damage: 8,
      cooldownMs: 3000,
      knockback: 0,
      firstDelayMs: 1800,
      lifeMs: 5000,
      aim: 'nearest',
      volley: { count: 5, spreadDeg: 70 },
      projectile: { emoji: '1f7e3', size: 0.42, radius: 0.15, speed: 3.2, rotationOffsetDeg: 0 },
    },
  ],
}

const RIVER_BOSS: EnemyDef = {
  kind: 'croc',
  role: 'boss',
  emoji: '1f40a',
  name: '巨鳄',
  desc: '奔流头目：喷吐水弹扇幕，掀起水柱自天砸落，击退免疫',
  size: 3.4,
  radius: 1.1,
  hp: 6200,
  speed: 1.3,
  damage: 20,
  xp: 60,
  coins: 60,
  kbImmune: true,
  locomotion: { kind: 'chase' },
  abilities: [
    {
      kind: 'projectile',
      damage: 9,
      cooldownMs: 3200,
      knockback: 0,
      firstDelayMs: 1800,
      lifeMs: 5000,
      aim: 'nearest',
      volley: { count: 6, spreadDeg: 90 },
      projectile: { emoji: '1f4a7', size: 0.5, radius: 0.18, speed: 2.6, rotationOffsetDeg: 0 },
    },
    {
      kind: 'strike',
      damage: 22,
      cooldownMs: 5000,
      knockback: 0,
      targets: 4,
      drop: { emoji: '1f4a7', size: 1.0, fromAbove: 4, dropMs: 240, staggerMs: 80 },
    },
  ],
}

const FACTORY_BOSS: EnemyDef = {
  kind: 'mecha',
  role: 'boss',
  emoji: '1f916',
  name: '母机核心',
  desc: '工厂头目：激光点射与整圈环扫，液压重锤自天砸落，击退免疫',
  size: 3.4,
  radius: 1.1,
  hp: 6500,
  speed: 1.2,
  damage: 20,
  xp: 60,
  coins: 60,
  kbImmune: true,
  locomotion: { kind: 'chase' },
  abilities: [
    {
      kind: 'projectile',
      damage: 8,
      cooldownMs: 2400,
      knockback: 0,
      firstDelayMs: 1600,
      lifeMs: 6000,
      aim: 'nearest',
      fireSfx: 'boom',
      everyN: { n: 3, count: 12, spreadDeg: 360 },
      projectile: { emoji: '1f534', size: 0.4, radius: 0.14, speed: 3.2, rotationOffsetDeg: 0 },
    },
    {
      kind: 'strike',
      damage: 24,
      cooldownMs: 4800,
      knockback: 0,
      targets: 5,
      drop: { emoji: '1f528', size: 1.1, fromAbove: 4, dropMs: 220, staggerMs: 80 },
    },
  ],
}


const RUINS_BOSS: EnemyDef = {
  kind: 'rhino',
  role: 'boss',
  emoji: '1f98f',
  name: '拆迁鬼',
  desc: '残垣头目：犀角冲撞碾碎沿途断壁，落石从天砸下无视遮挡，击退免疫',
  size: 3.2,
  radius: 1.05,
  hp: 6000,
  speed: 1.4,
  damage: 20,
  xp: 60,
  coins: 60,
  kbImmune: true,
  breaksWalls: true,
  locomotion: {
    kind: 'dash',
    trigger: { kind: 'timer', intervalMs: 5000, firstDelayMs: 3200 },
    length: { kind: 'time', durationMs: 600 },
    windupMs: 700,
    dashSpeed: 10,
    idle: 'chase',
    aim: 'teamCenter',
    lockAt: 'launch',
    sfx: 'whoosh',
  },
  abilities: [
    {
      kind: 'strike',
      damage: 24,
      cooldownMs: 4500,
      knockback: 0,
      targets: 5,
      drop: { emoji: '1faa8', size: 1.1, fromAbove: 4, dropMs: 240, staggerMs: 90 },
    },
  ],
}

const DAYNIGHT_BOSS: EnemyDef = {
  kind: 'eclipse',
  role: 'boss',
  emoji: '1f317',
  name: '晦明',
  desc: '晨昏原野头目：阳面喷洒日冕环爆，阴面召落月华坠，昼夜轮替、击退免疫',
  size: 3.4,
  radius: 1.1,
  hp: 6300,
  speed: 1.25,
  damage: 20,
  xp: 60,
  coins: 60,
  kbImmune: true,
  locomotion: { kind: 'chase' },
  abilities: [
    {
      kind: 'projectile',
      damage: 8,
      cooldownMs: 3000,
      knockback: 0,
      firstDelayMs: 1600,
      lifeMs: 5000,
      aim: 'nearest',
      volley: { count: 14, spreadDeg: 360 },
      projectile: { emoji: '1f31f', size: 0.5, radius: 0.18, speed: 2.5, rotationOffsetDeg: 0 },
    },
    {
      kind: 'strike',
      damage: 22,
      cooldownMs: 4600,
      knockback: 0,
      targets: 4,
      drop: { emoji: '1f319', size: 1.0, fromAbove: 4, dropMs: 240, staggerMs: 80 },
    },
  ],
}

const SPACE_BOSS: EnemyDef = {
  kind: 'blackhole',
  role: 'boss',
  emoji: '1f300',
  name: '奇点',
  desc: '太空头目：张开禁锢力场令谁也逃不出，吸积盘环爆 + 奇点坍缩坠击，击退免疫',
  size: 3.4,
  radius: 1.1,
  hp: 6600,
  speed: 1.15,
  damage: 20,
  xp: 60,
  coins: 60,
  kbImmune: true,
  locomotion: { kind: 'chase' },
  abilities: [
    {
      kind: 'projectile',
      damage: 8,
      cooldownMs: 2800,
      knockback: 0,
      firstDelayMs: 1600,
      lifeMs: 5000,
      aim: 'nearest',
      volley: { count: 16, spreadDeg: 360 },
      projectile: { emoji: '1f4ab', size: 0.5, radius: 0.18, speed: 2.5, rotationOffsetDeg: 0 },
    },
    {
      kind: 'strike',
      damage: 22,
      cooldownMs: 4600,
      knockback: 0,
      targets: 4,
      drop: { emoji: '1f311', size: 1.0, fromAbove: 4, dropMs: 240, staggerMs: 80 },
    },
  ],
}

/** 顺序即图鉴展示顺序 */
export const ENEMIES = Object.fromEntries(
  [...ENEMY_DEFS, FOREST_BOSS, DESERT_BOSS, RIVER_BOSS, FACTORY_BOSS, RUINS_BOSS, DAYNIGHT_BOSS, SPACE_BOSS].map((e) => [e.kind, e]),
) as Record<string, EnemyDef>
