import type { ItemDef } from '../src/types/items'

export const ITEMS = {
  gemHeart: {
    emoji: '2764',
    name: '生命宝石',
    desc: '生命上限 +25',
    rarity: 'common',
    price: 15,
    pool: 'all',
    upgradeXp: 10,
    effects: { hpAdd: 25 },
  },
  shellArmor: {
    emoji: '1f6e1',
    name: '硬壳护甲',
    desc: '生命上限 +60 · 攻速 -10%',
    rarity: 'common',
    price: 20,
    maxStacks: 3,
    pool: 'all',
    upgradeXp: 12,
    effects: { hpAdd: 60, cooldownMul: 1.1 },
  },
  stimulant: {
    emoji: '26a1',
    name: '兴奋剂',
    desc: '攻速 +15% · 生命上限 -10',
    rarity: 'common',
    price: 25,
    maxStacks: 5,
    pool: 'all',
    upgradeXp: 13,
    effects: { cooldownMul: 0.87, hpAdd: -10 },
  },
  whetstone: {
    emoji: '1f5e1',
    name: '磨刀石',
    desc: '伤害 +12%',
    rarity: 'common',
    price: 25,
    pool: 'all',
    upgradeXp: 13,
    effects: { damageMul: 1.12 },
  },
  rageBracer: {
    emoji: '1f4aa',
    name: '狂暴护腕',
    desc: '伤害 +25% · 生命上限 -20',
    rarity: 'common',
    price: 30,
    maxStacks: 3,
    pool: 'all',
    upgradeXp: 15,
    effects: { damageMul: 1.25, hpAdd: -20 },
  },
  padHelmet: {
    emoji: '26d1',
    name: '缓冲头盔',
    desc: '受击无敌 +0.15 秒',
    rarity: 'common',
    price: 18,
    maxStacks: 3,
    pool: 'all',
    upgradeXp: 11,
    effects: { iframesAddMs: 150 },
  },
  reviveWatch: {
    emoji: '23f1',
    name: '复活怀表',
    desc: '复活时间 -2 秒',
    rarity: 'common',
    price: 22,
    maxStacks: 3,
    pool: 'all',
    upgradeXp: 12,
    effects: { reviveAddMs: -2000 },
  },
  regenRing: {
    emoji: '1f48d',
    name: '再生戒指',
    desc: '每秒回复 2 生命',
    rarity: 'rare',
    price: 45,
    maxStacks: 3,
    pool: 'all',
    upgradeXp: 26,
    effects: { regenPerSec: 2 },
  },
  thornVest: {
    emoji: '1f335',
    name: '荆棘背心',
    desc: '敌人接触时受到 14 反伤',
    rarity: 'rare',
    price: 45,
    maxStacks: 3,
    pool: 'all',
    upgradeXp: 26,
    effects: { thorns: 14 },
  },
  vampFang: {
    emoji: '1f9db',
    name: '吸血獠牙',
    desc: '击杀敌人回复 3 生命',
    rarity: 'rare',
    price: 50,
    maxStacks: 2,
    pool: 'all',
    upgradeXp: 28,
    effects: { killHeal: 3 },
  },
  hammerWeight: {
    emoji: '1f528',
    name: '重锤配重',
    desc: '能力击退 +35%',
    rarity: 'rare',
    price: 40,
    maxStacks: 2,
    pool: 'all',
    upgradeXp: 24,
    effects: { knockbackMul: 1.35 },
  },
  fateDice: {
    emoji: '1f3b2',
    name: '命运骰子',
    desc: '20% 概率暴击，伤害翻倍',
    rarity: 'epic',
    price: 95,
    maxStacks: 2,
    pool: 'all',
    upgradeXp: 55,
    minLevel: 2,
    effects: { critChance: 0.2 },
  },
  giantHeart: {
    emoji: '1fac0',
    name: '巨人心脏',
    desc: '生命上限 +150',
    rarity: 'epic',
    price: 90,
    maxStacks: 2,
    pool: 'all',
    upgradeXp: 52,
    minLevel: 3,
    effects: { hpAdd: 150 },
  },
  phaseCloak: {
    emoji: '1f32b',
    name: '相位披风',
    desc: '受击无敌 +0.4 秒',
    rarity: 'epic',
    price: 100,
    maxStacks: 2,
    pool: 'all',
    upgradeXp: 56,
    minLevel: 2,
    effects: { iframesAddMs: 400 },
  },
  blastPowder: {
    emoji: '1f4a5',
    name: '扩爆火药',
    desc: '轰炸范围 +20%',
    rarity: 'common',
    price: 25,
    maxStacks: 3,
    pool: 'areaBlast',
    upgradeXp: 12,
    effects: { rangeMul: 1.2 },
  },
  scope: {
    emoji: '1f3af',
    name: '瞄准镜',
    desc: '弹速 +25%',
    rarity: 'common',
    price: 20,
    maxStacks: 2,
    pool: 'projectile',
    upgradeXp: 11,
    effects: { projSpeedMul: 1.25 },
  },
  powerCell: {
    emoji: '1f50b',
    name: '高能电池',
    desc: '激光范围 +20%',
    rarity: 'common',
    price: 22,
    maxStacks: 3,
    pool: 'laser',
    upgradeXp: 11,
    effects: { rangeMul: 1.2 },
  },
  longHaft: {
    emoji: '1f32a',
    name: '长柄套件',
    desc: '横扫范围 +15% · 攻速 -5%',
    rarity: 'common',
    price: 22,
    maxStacks: 3,
    pool: 'sweep',
    upgradeXp: 12,
    effects: { rangeMul: 1.15, cooldownMul: 1.05 },
  },
  lance: {
    emoji: '1f9af',
    name: '加长枪杆',
    desc: '突刺范围 +20%',
    rarity: 'common',
    price: 20,
    maxStacks: 3,
    pool: 'thrust',
    upgradeXp: 11,
    effects: { rangeMul: 1.2 },
  },
  returnString: {
    emoji: '1f9f5',
    name: '回力丝线',
    desc: '回旋镖范围 +20%',
    rarity: 'common',
    price: 20,
    maxStacks: 3,
    pool: 'boomerang',
    upgradeXp: 11,
    effects: { rangeMul: 1.2 },
  },
  frostCore: {
    emoji: '1f9ca',
    name: '深寒结晶',
    desc: '光环范围 +20%',
    rarity: 'common',
    price: 24,
    maxStacks: 3,
    pool: 'slowAura',
    upgradeXp: 12,
    effects: { rangeMul: 1.2 },
  },
} as const satisfies Record<string, ItemDef>
