import { CHARACTERS, characterCard } from './characters.ts'
import type { CharacterId } from '../src/characters/registry'
import type { ItemDef } from '../src/items/registry'

// 创作层（不进运行时 bundle）：道具数据行；升级卡文案在生成时从角色载体的
// 档位派生（多载体同档去重）。生成 src/assets/items.json。

/** 角色专属升级卡条目（文案/图标取自角色该档升级卡） */
function upgradeCard(cid: CharacterId, index: 0 | 1, price: number): ItemDef {
  const a = characterCard(CHARACTERS[cid], index)
  return {
    emoji: a.icon,
    name: a.name,
    desc: a.desc,
    rarity: index === 0 ? 'rare' : 'epic',
    price,
    maxStacks: 1,
    pool: 'upgrade',
    forCharacter: cid,
    abilityIndex: index,
    effects: {},
  }
}

export const ITEMS = {
  // ── 通用池 · 普通（15~35）──
  gemHeart: {
    emoji: '2764',
    name: '生命宝石',
    desc: '生命上限 +25',
    rarity: 'common',
    price: 15,
    pool: 'all',
    effects: { hpAdd: 25 },
  },
  shellArmor: {
    emoji: '1f6e1',
    name: '硬壳护甲',
    desc: '生命上限 +60 · 攻速 -10%',
    rarity: 'common',
    price: 20,
    maxStacks: 3,
    pool: 'all',
    effects: { hpAdd: 60, cooldownMul: 1.1 },
  },
  stimulant: {
    emoji: '26a1',
    name: '兴奋剂',
    desc: '攻速 +15% · 生命上限 -10',
    rarity: 'common',
    price: 25,
    maxStacks: 5,
    pool: 'all',
    effects: { cooldownMul: 0.87, hpAdd: -10 },
  },
  whetstone: {
    emoji: '1f5e1',
    name: '磨刀石',
    desc: '伤害 +12%',
    rarity: 'common',
    price: 25,
    pool: 'all',
    effects: { damageMul: 1.12 },
  },
  rageBracer: {
    emoji: '1f4aa',
    name: '狂暴护腕',
    desc: '伤害 +25% · 生命上限 -20',
    rarity: 'common',
    price: 30,
    maxStacks: 3,
    pool: 'all',
    effects: { damageMul: 1.25, hpAdd: -20 },
  },
  padHelmet: {
    emoji: '26d1',
    name: '缓冲头盔',
    desc: '受击无敌 +0.15 秒',
    rarity: 'common',
    price: 18,
    maxStacks: 3,
    pool: 'all',
    effects: { iframesAddMs: 150 },
  },
  reviveWatch: {
    emoji: '23f1',
    name: '复活怀表',
    desc: '复活时间 -2 秒',
    rarity: 'common',
    price: 22,
    maxStacks: 3,
    pool: 'all',
    effects: { reviveAddMs: -2000 },
  },
  // ── 通用池 · 稀有（40~55）──
  regenRing: {
    emoji: '1f48d',
    name: '再生戒指',
    desc: '每秒回复 2 生命',
    rarity: 'rare',
    price: 45,
    maxStacks: 3,
    pool: 'all',
    effects: { regenPerSec: 2 },
  },
  thornVest: {
    emoji: '1f335',
    name: '荆棘背心',
    desc: '敌人接触时受到 14 反伤',
    rarity: 'rare',
    price: 45,
    maxStacks: 3,
    pool: 'all',
    effects: { thorns: 14 },
  },
  vampFang: {
    emoji: '1f9db',
    name: '吸血獠牙',
    desc: '击杀敌人回复 3 生命',
    rarity: 'rare',
    price: 50,
    maxStacks: 2,
    pool: 'all',
    effects: { killHeal: 3 },
  },
  hammerWeight: {
    emoji: '1f528',
    name: '重锤配重',
    desc: '能力击退 +35%',
    rarity: 'rare',
    price: 40,
    maxStacks: 2,
    pool: 'all',
    effects: { knockbackMul: 1.35 },
  },
  // ── 通用池 · 史诗（90~130）──
  fateDice: {
    emoji: '1f3b2',
    name: '命运骰子',
    desc: '20% 概率暴击，伤害翻倍',
    rarity: 'epic',
    price: 95,
    maxStacks: 2,
    pool: 'all',
    effects: { critChance: 0.2 },
  },
  giantHeart: {
    emoji: '1fac0',
    name: '巨人心脏',
    desc: '生命上限 +150',
    rarity: 'epic',
    price: 90,
    maxStacks: 2,
    pool: 'all',
    effects: { hpAdd: 150 },
  },
  phaseCloak: {
    emoji: '1f32b',
    name: '相位披风',
    desc: '受击无敌 +0.4 秒',
    rarity: 'epic',
    price: 100,
    maxStacks: 2,
    pool: 'all',
    effects: { iframesAddMs: 400 },
  },
  // ── 能力形态专属池（普通） ──
  blastPowder: {
    emoji: '1f4a5',
    name: '扩爆火药',
    desc: '轰炸范围 +20%',
    rarity: 'common',
    price: 25,
    maxStacks: 3,
    pool: 'areaBlast',
    effects: { rangeMul: 1.2 },
  },
  scope: {
    emoji: '1f3af',
    name: '瞄准镜',
    desc: '弹速 +25%',
    rarity: 'common',
    price: 20,
    maxStacks: 2,
    pool: 'projectile',
    effects: { projSpeedMul: 1.25 },
  },
  powerCell: {
    emoji: '1f50b',
    name: '高能电池',
    desc: '激光范围 +20%',
    rarity: 'common',
    price: 22,
    maxStacks: 3,
    pool: 'laser',
    effects: { rangeMul: 1.2 },
  },
  longHaft: {
    emoji: '1f32a',
    name: '长柄套件',
    desc: '横扫范围 +15% · 攻速 -5%',
    rarity: 'common',
    price: 22,
    maxStacks: 3,
    pool: 'sweep',
    effects: { rangeMul: 1.15, cooldownMul: 1.05 },
  },
  lance: {
    emoji: '1f9af',
    name: '加长枪杆',
    desc: '突刺范围 +20%',
    rarity: 'common',
    price: 20,
    maxStacks: 3,
    pool: 'thrust',
    effects: { rangeMul: 1.2 },
  },
  returnString: {
    emoji: '1f9f5',
    name: '回力丝线',
    desc: '回旋镖范围 +20%',
    rarity: 'common',
    price: 20,
    maxStacks: 3,
    pool: 'boomerang',
    effects: { rangeMul: 1.2 },
  },
  frostCore: {
    emoji: '1f9ca',
    name: '深寒结晶',
    desc: '光环范围 +20%',
    rarity: 'common',
    price: 24,
    maxStacks: 3,
    pool: 'slowAura',
    effects: { rangeMul: 1.2 },
  },
  // 团队增益已从「队长道具」迁移到经验升级卡（见 cards/registry.ts），商店只卖角色装备
  // ── 角色专属升级卡（一阶 稀有 / 二阶 史诗；价格高一档，质变值这个价）──
  upgradeJuggler1: upgradeCard('juggler', 0, 80),
  upgradeJuggler2: upgradeCard('juggler', 1, 150),
  upgradeUnicorn1: upgradeCard('unicorn', 0, 80),
  upgradeUnicorn2: upgradeCard('unicorn', 1, 150),
  upgradeTroll1: upgradeCard('troll', 0, 80),
  upgradeTroll2: upgradeCard('troll', 1, 150),
  upgradeCowboy1: upgradeCard('cowboy', 0, 80),
  upgradeCowboy2: upgradeCard('cowboy', 1, 150),
  upgradeMage1: upgradeCard('mage', 0, 80),
  upgradeMage2: upgradeCard('mage', 1, 150),
  upgradeKangaroo1: upgradeCard('kangaroo', 0, 80),
  upgradeKangaroo2: upgradeCard('kangaroo', 1, 150),
  upgradeRobot1: upgradeCard('robot', 0, 80),
  upgradeRobot2: upgradeCard('robot', 1, 150),
  upgradeSnowman1: upgradeCard('snowman', 0, 80),
  upgradeSnowman2: upgradeCard('snowman', 1, 150),
  upgradeFairy1: upgradeCard('fairy', 0, 80),
  upgradeFairy2: upgradeCard('fairy', 1, 150),
  upgradeAssassin1: upgradeCard('assassin', 0, 80),
  upgradeAssassin2: upgradeCard('assassin', 1, 150),
  upgradeBeaver1: upgradeCard('beaver', 0, 80),
  upgradeBeaver2: upgradeCard('beaver', 1, 150),
  upgradeQueenBee1: upgradeCard('queenBee', 0, 80),
  upgradeQueenBee2: upgradeCard('queenBee', 1, 150),
  upgradeMedic1: upgradeCard('medic', 0, 80),
  upgradeMedic2: upgradeCard('medic', 1, 150),
  upgradeJellyfish1: upgradeCard('jellyfish', 0, 80),
  upgradeJellyfish2: upgradeCard('jellyfish', 1, 150),
} as const satisfies Record<string, ItemDef>
