import type { ItemDef } from '../src/types/items'

export const ITEMS = {
  gemHeart: {
    emoji: '2764',
    name: '生命宝石',
    rarity: 'common',
    price: 15,
    stats: { add: { maxHp: 25 } },
  },
  shellArmor: {
    emoji: '1f6e1',
    name: '硬壳护甲',
    rarity: 'common',
    price: 20,
    maxStacks: 3,
    stats: { add: { maxHp: 60 }, mul: { cooldown: 1.1 } },
  },
  stimulant: {
    emoji: '26a1',
    name: '兴奋剂',
    rarity: 'common',
    price: 25,
    maxStacks: 5,
    stats: { add: { maxHp: -10 }, mul: { cooldown: 0.87 } },
  },
  whetstone: {
    emoji: '1f5e1',
    name: '磨刀石',
    rarity: 'common',
    price: 25,
    stats: { mul: { damage: 1.12 } },
  },
  rageBracer: {
    emoji: '1f4aa',
    name: '狂暴护腕',
    rarity: 'common',
    price: 30,
    maxStacks: 3,
    stats: { add: { maxHp: -20 }, mul: { damage: 1.25 } },
  },
  padHelmet: {
    emoji: '26d1',
    name: '缓冲头盔',
    rarity: 'common',
    price: 18,
    maxStacks: 3,
    stats: { add: { iframes: 150 } },
  },
  reviveWatch: {
    emoji: '23f1',
    name: '复活怀表',
    rarity: 'common',
    price: 22,
    maxStacks: 3,
    stats: { add: { revive: -2000 } },
  },
  helmet: {
    emoji: '1fa96',
    name: '钢盔',
    rarity: 'common',
    price: 18,
    stats: { add: { armor: 2 }, mul: { moveSpeed: 0.97 } },
  },
  espresso: {
    emoji: '2615',
    name: '浓咖啡',
    rarity: 'common',
    price: 20,
    stats: { mul: { cooldown: 0.909, damage: 0.97 } },
  },
  evilEye: {
    emoji: '1f9ff',
    name: '邪眼',
    rarity: 'common',
    price: 20,
    stats: { add: { crit: 0.06 }, mul: { damage: 0.97 } },
  },
  sneakers: {
    emoji: '1f45f',
    name: '跑鞋',
    rarity: 'common',
    price: 18,
    stats: { add: { armor: -1 }, mul: { moveSpeed: 1.08 } },
  },
  cushion: {
    emoji: '1f9d8',
    name: '蒲团',
    rarity: 'common',
    price: 22,
    stats: { mul: { skillCooldown: 0.893, cooldown: 1.05 } },
  },
  boxingGlove: {
    emoji: '1f94a',
    name: '拳套',
    rarity: 'common',
    price: 22,
    for: ['melee'],
    stats: { mul: { meleeDamage: 1.15, range: 0.92 } },
  },
  telescope: {
    emoji: '1f52d',
    name: '望远镜',
    rarity: 'common',
    price: 22,
    for: ['ranged'],
    stats: { mul: { rangedDamage: 1.12, moveSpeed: 0.97 } },
  },
  dynamite: {
    emoji: '1f9e8',
    name: '雷管',
    rarity: 'common',
    price: 20,
    for: ['area'],
    stats: { mul: { areaDamage: 1.2, taken: 1.03 } },
  },
  venomVial: {
    emoji: '1f9ea',
    name: '毒液瓶',
    rarity: 'common',
    price: 22,
    for: ['dot'],
    stats: { add: { maxHp: -10 }, mul: { dotDamage: 1.25 } },
  },
  wrench: {
    emoji: '1f527',
    name: '扳手',
    rarity: 'common',
    price: 20,
    for: ['summon'],
    stats: { mul: { summonDamage: 1.2, damage: 0.97 } },
  },
  bandage: {
    emoji: '1fa79',
    name: '绷带',
    rarity: 'common',
    price: 18,
    for: ['heal'],
    stats: { mul: { healing: 1.25 } },
  },
  blastPowder: {
    emoji: '1f4a5',
    name: '扩爆火药',
    rarity: 'common',
    price: 25,
    maxStacks: 3,
    for: ['disc'],
    stats: { mul: { range: 1.2 } },
  },
  scope: {
    emoji: '1f3af',
    name: '瞄准镜',
    rarity: 'common',
    price: 20,
    maxStacks: 2,
    for: ['bolt'],
    stats: { mul: { projSpeed: 1.25 } },
  },
  powerCell: {
    emoji: '1f50b',
    name: '高能电池',
    rarity: 'common',
    price: 22,
    maxStacks: 3,
    for: ['segment'],
    stats: { mul: { range: 1.2 } },
  },
  longHaft: {
    emoji: '1f32a',
    name: '长柄套件',
    rarity: 'common',
    price: 22,
    maxStacks: 3,
    for: ['sector'],
    stats: { mul: { range: 1.15, cooldown: 1.05 } },
  },
  returnString: {
    emoji: '1f9f5',
    name: '回力丝线',
    rarity: 'common',
    price: 20,
    maxStacks: 3,
    for: ['flyer'],
    stats: { mul: { range: 1.2 } },
  },
  frostCore: {
    emoji: '1f9ca',
    name: '深寒结晶',
    rarity: 'common',
    price: 24,
    maxStacks: 3,
    for: ['zone'],
    stats: { mul: { range: 1.2 } },
  },
  regenRing: {
    emoji: '1f48d',
    name: '再生戒指',
    rarity: 'rare',
    price: 45,
    maxStacks: 3,
    stats: { add: { regen: 2 } },
  },
  thornVest: {
    emoji: '1f335',
    name: '荆棘背心',
    rarity: 'rare',
    price: 45,
    maxStacks: 3,
    stats: { add: { thorns: 14 } },
  },
  vampFang: {
    emoji: '1f9b7',
    name: '吸血獠牙',
    rarity: 'rare',
    price: 50,
    maxStacks: 2,
    stats: { add: { killHeal: 3 } },
  },
  hammerWeight: {
    emoji: '1f528',
    name: '重锤配重',
    rarity: 'rare',
    price: 40,
    maxStacks: 2,
    stats: { mul: { knockback: 1.35 } },
  },
  bloodBeads: {
    emoji: '1f4ff',
    name: '血色念珠',
    rarity: 'rare',
    price: 40,
    stats: { add: { lifesteal: 0.03, maxHp: -10 } },
  },
  ironPlate: {
    emoji: '1f529',
    name: '铁板',
    rarity: 'rare',
    price: 40,
    stats: { add: { armor: 4 }, mul: { damage: 0.95 } },
  },
  sunglasses: {
    emoji: '1f576',
    name: '墨镜',
    rarity: 'rare',
    price: 45,
    stats: { add: { crit: 0.1, armor: -2 } },
  },
  keenKnife: {
    emoji: '1f52a',
    name: '开刃刀',
    rarity: 'rare',
    price: 45,
    stats: { mul: { critDamage: 1.25, cooldown: 1.05 } },
  },
  medal: {
    emoji: '1f396',
    name: '勋章',
    rarity: 'rare',
    price: 55,
    stats: { add: { maxHp: 20, armor: 1, crit: -0.04 }, mul: { damage: 1.03, moveSpeed: 1.03 } },
  },
  silverBullet: {
    emoji: '1f948',
    name: '银弹',
    rarity: 'rare',
    price: 45,
    stats: { mul: { bossDamage: 1.3 } },
  },
  ammoBox: {
    emoji: '1f9f0',
    name: '弹药箱',
    rarity: 'rare',
    price: 50,
    for: ['ranged'],
    stats: { add: { maxHp: -15 }, mul: { rangedDamage: 1.25 } },
  },
  warHammer: {
    emoji: '2692',
    name: '战锤',
    rarity: 'rare',
    price: 50,
    for: ['melee'],
    stats: { mul: { meleeDamage: 1.25, moveSpeed: 0.95 } },
  },
  fateDice: {
    emoji: '1f3b2',
    name: '命运骰子',
    rarity: 'epic',
    price: 95,
    maxStacks: 2,
    minLevel: 2,
    stats: { add: { crit: 0.2 } },
  },
  giantHeart: {
    emoji: '1fac0',
    name: '巨人心脏',
    rarity: 'epic',
    price: 90,
    maxStacks: 2,
    minLevel: 3,
    stats: { add: { maxHp: 150 } },
  },
  phaseCloak: {
    emoji: '1f32b',
    name: '相位披风',
    rarity: 'epic',
    price: 100,
    maxStacks: 2,
    minLevel: 2,
    stats: { add: { iframes: 400 } },
  },
  glassCannon: {
    emoji: '1f37e',
    name: '玻璃大炮',
    rarity: 'epic',
    price: 75,
    stats: { add: { armor: -3 }, mul: { damage: 1.25 } },
  },
  cloak: {
    emoji: '1f9e5',
    name: '隐身斗篷',
    rarity: 'epic',
    price: 80,
    stats: { add: { dodge: 0.15, armor: -3 }, mul: { moveSpeed: 0.97 } },
  },
  potato: {
    emoji: '1f954',
    name: '土豆',
    rarity: 'legendary',
    price: 100,
    stats: {
      add: { maxHp: 15, regen: 1, lifesteal: 0.01, dodge: 0.03, armor: 1 },
      mul: { damage: 1.05, cooldown: 0.952, moveSpeed: 1.03 },
    },
  },
  mammoth: {
    emoji: '1f9a3',
    name: '猛犸',
    rarity: 'legendary',
    price: 110,
    for: ['melee'],
    stats: { add: { regen: 3 }, mul: { meleeDamage: 1.4, knockback: 1.5, damage: 0.92, moveSpeed: 0.97 } },
  },
} as const satisfies Record<string, ItemDef>
