import type { CharacterId } from '../src/types/characters'
import type { StatMods } from '../src/types/stats'

export const LEVEL_STATS = {
  juggler: [{ add: { maxHp: 15 }, mul: { damage: 1.2 } }, { add: { maxHp: 35 }, mul: { damage: 1.45, cooldown: 0.9 } }],
  unicorn: [{ add: { maxHp: 25 }, mul: { damage: 1.25 } }, { add: { maxHp: 50 }, mul: { damage: 1.55 } }],
  troll: [{ add: { maxHp: 70 }, mul: { damage: 1.12 } }, { add: { maxHp: 170 }, mul: { damage: 1.28 } }],
  cowboy: [{ add: { maxHp: 15 }, mul: { cooldown: 0.88 } }, { add: { maxHp: 30 }, mul: { cooldown: 0.75, damage: 1.2 } }],
  mage: [{ add: { maxHp: 10 }, mul: { damage: 1.3 } }, { add: { maxHp: 25 }, mul: { damage: 1.65 } }],
  kangaroo: [{ add: { maxHp: 25 }, mul: { damage: 1.2 } }, { add: { maxHp: 55 }, mul: { damage: 1.45, range: 1.15 } }],
  robot: [{ add: { maxHp: 40 }, mul: { damage: 1.2 } }, { add: { maxHp: 90 }, mul: { damage: 1.4 } }],
  snowman: [{ add: { maxHp: 50 }, mul: { damage: 1.15 } }, { add: { maxHp: 120 }, mul: { damage: 1.3 } }],
  fairy: [{ add: { maxHp: 20 }, mul: { cooldown: 0.85 } }, { add: { maxHp: 45 }, mul: { cooldown: 0.72 } }],
  assassin: [{ add: { crit: 0.1 }, mul: { damage: 1.3 } }, { add: { crit: 0.2, maxHp: 20 }, mul: { damage: 1.6 } }],
  beaver: [{ add: { maxHp: 40 }, mul: { damage: 1.15 } }, { add: { maxHp: 100 }, mul: { damage: 1.3 } }],
  queenBee: [{ add: { maxHp: 30 }, mul: { damage: 1.2 } }, { add: { maxHp: 70 }, mul: { damage: 1.45 } }],
  medic: [{ add: { maxHp: 40 }, mul: { damage: 1.2, healing: 1.2 } }, { add: { maxHp: 90 }, mul: { damage: 1.45, healing: 1.45 } }],
  jellyfish: [{ add: { maxHp: 20 }, mul: { damage: 1.25 } }, { add: { maxHp: 45 }, mul: { damage: 1.5 } }],
  frog: [{ add: { maxHp: 25 }, mul: { damage: 1.2 } }, { add: { maxHp: 55 }, mul: { damage: 1.45 } }],
  fox: [{ add: { maxHp: 15 }, mul: { damage: 1.25 } }, { add: { maxHp: 35 }, mul: { damage: 1.5 } }],
  fencer: [{ add: { crit: 0.05 }, mul: { damage: 1.25 } }, { add: { crit: 0.12, maxHp: 20 }, mul: { damage: 1.55 } }],
  sloth: [{ add: { maxHp: 30 }, mul: { damage: 1.25 } }, { add: { maxHp: 60 }, mul: { damage: 1.5 } }],
  blackCat: [{ add: { maxHp: 10 }, mul: { damage: 1.25 } }, { add: { maxHp: 25 }, mul: { damage: 1.55 } }],
  gorilla: [{ add: { maxHp: 60 }, mul: { damage: 1.12 } }, { add: { maxHp: 150 }, mul: { damage: 1.3 } }],
  detective: [{ add: { maxHp: 20 }, mul: { damage: 1.25 } }, { add: { maxHp: 40 }, mul: { damage: 1.5 } }],
  eagle: [{ add: { maxHp: 20 }, mul: { damage: 1.25 } }, { add: { maxHp: 45 }, mul: { damage: 1.5 } }],
  bear: [{ add: { maxHp: 60 }, mul: { damage: 1.15 } }, { add: { maxHp: 140 }, mul: { damage: 1.32 } }],
  vampire: [{ add: { maxHp: 30 }, mul: { damage: 1.2, healing: 1.2 } }, { add: { maxHp: 60 }, mul: { damage: 1.45, healing: 1.45 } }],
  genie: [{ add: { maxHp: 15 }, mul: { damage: 1.25 } }, { add: { maxHp: 35 }, mul: { damage: 1.5 } }],
  parrot: [{ add: { maxHp: 15 }, mul: { cooldown: 0.88 } }, { add: { maxHp: 35 }, mul: { cooldown: 0.75 } }],
  panda: [{ add: { maxHp: 50 }, mul: { damage: 1.15 } }, { add: { maxHp: 120 }, mul: { damage: 1.3 } }],
  chipmunk: [{ add: { maxHp: 15 }, mul: { damage: 1.2 } }, { add: { maxHp: 35 }, mul: { damage: 1.45 } }],
  guard: [{ add: { maxHp: 70 }, mul: { damage: 1.12 } }, { add: { maxHp: 160 }, mul: { damage: 1.28 } }],
  peacock: [{ add: { maxHp: 15 }, mul: { damage: 1.2 } }, { add: { maxHp: 35 }, mul: { damage: 1.45 } }],
  koala: [{ add: { maxHp: 50 }, mul: { cooldown: 0.9 } }, { add: { maxHp: 120 }, mul: { cooldown: 0.78 } }],
  octopus: [{ add: { maxHp: 25 }, mul: { damage: 1.2 } }, { add: { maxHp: 50 }, mul: { damage: 1.45 } }],
  penguin: [{ add: { maxHp: 35 }, mul: { damage: 1.2 } }, { add: { maxHp: 70 }, mul: { damage: 1.45 } }],
  caterpillar: [{ add: { maxHp: 30 }, mul: { damage: 1.2 } }, { add: { maxHp: 60 }, mul: { damage: 1.45 } }],
  dragon: [{ add: { maxHp: 35 }, mul: { damage: 1.2 } }, { add: { maxHp: 70 }, mul: { damage: 1.45 } }],
  clown: [{ add: { maxHp: 15 }, mul: { damage: 1.25 } }, { add: { maxHp: 35 }, mul: { damage: 1.5 } }],
} as const satisfies Record<CharacterId, readonly StatMods[]>
