import { hslToInt } from '../src/util/palette.ts'
import type { MapDef } from '../src/types/maps'
import type { EnemyMixRow } from '../src/types/enemies'

const FOREST_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 80, perWave: -2, min: 40, max: 80 },
  { kind: 'ghost', sinceWave: 1, base: 15, perWave: 1, min: 12, max: 30 },
  { kind: 'locust', sinceWave: 2, base: 14, perWave: 0.6, min: 0, max: 28 },
  { kind: 'slime', sinceWave: 2, base: 12, perWave: 0.4, min: 0, max: 22 },
  { kind: 'boar', sinceWave: 3, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'mushroom', sinceWave: 4, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'elf', sinceWave: 5, base: 4, perWave: 0.3, min: 0, max: 9 },
  { kind: 'chameleon', sinceWave: 3, base: 6, perWave: 0.3, min: 0, max: 12 },
]

const MEADOW_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 80, perWave: -2, min: 40, max: 80 },
  { kind: 'locust', sinceWave: 1, base: 15, perWave: 0.8, min: 12, max: 30 },
  { kind: 'slime', sinceWave: 2, base: 12, perWave: 0.4, min: 0, max: 22 },
  { kind: 'boar', sinceWave: 2, base: 9, perWave: 0.4, min: 0, max: 16 },
  { kind: 'snake', sinceWave: 3, base: 8, perWave: 0.3, min: 0, max: 14 },
  { kind: 'mushroom', sinceWave: 4, base: 7, perWave: 0.3, min: 0, max: 14 },
  { kind: 'rat', sinceWave: 5, base: 5, perWave: 0.3, min: 0, max: 10 },
]

const DESERT_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 78, perWave: -2, min: 38, max: 78 },
  { kind: 'locust', sinceWave: 1, base: 16, perWave: 0.8, min: 12, max: 32 },
  { kind: 'boar', sinceWave: 2, base: 10, perWave: 0.4, min: 0, max: 18 },
  { kind: 'snake', sinceWave: 3, base: 9, perWave: 0.3, min: 0, max: 14 },
  { kind: 'rat', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'creeper', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'turtle', sinceWave: 5, base: 5, perWave: 0.3, min: 0, max: 10 },
  { kind: 'skeleton', sinceWave: 3, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'raccoon', sinceWave: 5, base: 4, perWave: 0.2, min: 0, max: 8 },
]

const RIVER_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 78, perWave: -2, min: 38, max: 78 },
  { kind: 'ghost', sinceWave: 1, base: 14, perWave: 0.8, min: 10, max: 28 },
  { kind: 'blob', sinceWave: 2, base: 12, perWave: 0.5, min: 0, max: 22 },
  { kind: 'slime', sinceWave: 2, base: 12, perWave: 0.4, min: 0, max: 22 },
  { kind: 'snake', sinceWave: 3, base: 9, perWave: 0.3, min: 0, max: 14 },
  { kind: 'puffer', sinceWave: 4, base: 6, perWave: 0.4, min: 0, max: 13 },
  { kind: 'turtle', sinceWave: 5, base: 5, perWave: 0.3, min: 0, max: 10 },
  { kind: 'siren', sinceWave: 3, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'crab', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
]

const FACTORY_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 76, perWave: -2, min: 36, max: 76 },
  { kind: 'invader', sinceWave: 1, base: 14, perWave: 0.6, min: 10, max: 26 },
  { kind: 'slime', sinceWave: 2, base: 12, perWave: 0.4, min: 0, max: 22 },
  { kind: 'creeper', sinceWave: 3, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'rat', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'gargoyle', sinceWave: 5, base: 5, perWave: 0.3, min: 0, max: 11 },
  { kind: 'puffer', sinceWave: 5, base: 5, perWave: 0.3, min: 0, max: 11 },
  { kind: 'hive', sinceWave: 7, base: 3, perWave: 0.15, min: 0, max: 6 },
  { kind: 'raccoon', sinceWave: 3, base: 5, perWave: 0.3, min: 0, max: 10 },
  { kind: 'knight', sinceWave: 4, base: 5, perWave: 0.3, min: 0, max: 10 },
]

const RUINS_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 78, perWave: -2, min: 38, max: 78 },
  { kind: 'ghost', sinceWave: 1, base: 18, perWave: 1, min: 14, max: 34 },
  { kind: 'mushroom', sinceWave: 3, base: 8, perWave: 0.4, min: 0, max: 15 },
  { kind: 'snake', sinceWave: 3, base: 9, perWave: 0.3, min: 0, max: 14 },
  { kind: 'creeper', sinceWave: 4, base: 7, perWave: 0.3, min: 0, max: 13 },
  { kind: 'gargoyle', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'elf', sinceWave: 5, base: 4, perWave: 0.3, min: 0, max: 9 },
  { kind: 'skeleton', sinceWave: 2, base: 10, perWave: 0.4, min: 0, max: 18 },
  { kind: 'knight', sinceWave: 5, base: 4, perWave: 0.3, min: 0, max: 9 },
]

const DAY_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 70, perWave: -2, min: 34, max: 70 },
  { kind: 'boar', sinceWave: 1, base: 18, perWave: 0.8, min: 12, max: 34 },
  { kind: 'locust', sinceWave: 1, base: 16, perWave: 0.8, min: 12, max: 32 },
  { kind: 'slime', sinceWave: 2, base: 12, perWave: 0.4, min: 0, max: 22 },
  { kind: 'invader', sinceWave: 3, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'knight', sinceWave: 3, base: 6, perWave: 0.3, min: 0, max: 12 },
]

const NIGHT_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 40, perWave: -1, min: 20, max: 40 },
  { kind: 'ghost', sinceWave: 1, base: 16, perWave: 1, min: 12, max: 30 },
  { kind: 'gargoyle', sinceWave: 2, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'snake', sinceWave: 3, base: 9, perWave: 0.3, min: 0, max: 14 },
  { kind: 'creeper', sinceWave: 3, base: 7, perWave: 0.3, min: 0, max: 13 },
  { kind: 'rat', sinceWave: 4, base: 5, perWave: 0.3, min: 0, max: 11 },
  { kind: 'chameleon', sinceWave: 2, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'skeleton', sinceWave: 3, base: 8, perWave: 0.4, min: 0, max: 16 },
]

const SPACE_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 74, perWave: -2, min: 36, max: 74 },
  { kind: 'invader', sinceWave: 1, base: 16, perWave: 0.7, min: 12, max: 30 },
  { kind: 'alien', sinceWave: 2, base: 14, perWave: 0.6, min: 0, max: 26 },
  { kind: 'comet', sinceWave: 3, base: 9, perWave: 0.4, min: 0, max: 17 },
  { kind: 'ufo', sinceWave: 4, base: 7, perWave: 0.4, min: 0, max: 14 },
  { kind: 'gargoyle', sinceWave: 5, base: 5, perWave: 0.3, min: 0, max: 11 },
  { kind: 'chameleon', sinceWave: 3, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'siren', sinceWave: 4, base: 5, perWave: 0.3, min: 0, max: 10 },
]

const ICE_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 78, perWave: -2, min: 38, max: 78 },
  { kind: 'boar', sinceWave: 1, base: 16, perWave: 0.8, min: 12, max: 32 },
  { kind: 'ghost', sinceWave: 2, base: 12, perWave: 0.5, min: 0, max: 24 },
  { kind: 'blob', sinceWave: 2, base: 12, perWave: 0.5, min: 0, max: 22 },
  { kind: 'snake', sinceWave: 3, base: 9, perWave: 0.3, min: 0, max: 14 },
  { kind: 'turtle', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'creeper', sinceWave: 5, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'crab', sinceWave: 2, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'knight', sinceWave: 4, base: 5, perWave: 0.3, min: 0, max: 10 },
]

const VOLCANO_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 74, perWave: -2, min: 36, max: 74 },
  { kind: 'turtle', sinceWave: 1, base: 14, perWave: 0.6, min: 10, max: 26 },
  { kind: 'creeper', sinceWave: 2, base: 10, perWave: 0.4, min: 0, max: 18 },
  { kind: 'skeleton', sinceWave: 2, base: 9, perWave: 0.4, min: 0, max: 16 },
  { kind: 'comet', sinceWave: 3, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'boar', sinceWave: 3, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'gargoyle', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
]

const SHIP_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 76, perWave: -2, min: 36, max: 76 },
  { kind: 'skeleton', sinceWave: 1, base: 14, perWave: 0.6, min: 10, max: 26 },
  { kind: 'rat', sinceWave: 2, base: 9, perWave: 0.4, min: 0, max: 16 },
  { kind: 'ghost', sinceWave: 2, base: 10, perWave: 0.5, min: 0, max: 20 },
  { kind: 'puffer', sinceWave: 3, base: 7, perWave: 0.3, min: 0, max: 13 },
  { kind: 'siren', sinceWave: 3, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'creeper', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'raccoon', sinceWave: 5, base: 4, perWave: 0.2, min: 0, max: 8 },
]

const NEBULA_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 72, perWave: -2, min: 34, max: 72 },
  { kind: 'alien', sinceWave: 1, base: 16, perWave: 0.7, min: 12, max: 30 },
  { kind: 'comet', sinceWave: 2, base: 11, perWave: 0.5, min: 0, max: 21 },
  { kind: 'ufo', sinceWave: 3, base: 8, perWave: 0.4, min: 0, max: 15 },
  { kind: 'siren', sinceWave: 3, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'chameleon', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'ghost', sinceWave: 5, base: 5, perWave: 0.3, min: 0, max: 10 },
]

const CAVE_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 74, perWave: -2, min: 36, max: 74 },
  { kind: 'skeleton', sinceWave: 1, base: 14, perWave: 0.6, min: 10, max: 26 },
  { kind: 'rat', sinceWave: 2, base: 9, perWave: 0.4, min: 0, max: 16 },
  { kind: 'slime', sinceWave: 2, base: 10, perWave: 0.4, min: 0, max: 18 },
  { kind: 'mushroom', sinceWave: 3, base: 8, perWave: 0.4, min: 0, max: 15 },
  { kind: 'creeper', sinceWave: 3, base: 7, perWave: 0.3, min: 0, max: 13 },
  { kind: 'gargoyle', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
  { kind: 'siren', sinceWave: 5, base: 4, perWave: 0.2, min: 0, max: 8 },
]

const CIRCUIT_MIX: readonly EnemyMixRow[] = [
  { kind: 'zombie', sinceWave: 1, base: 76, perWave: -2, min: 36, max: 76 },
  { kind: 'invader', sinceWave: 1, base: 14, perWave: 0.6, min: 10, max: 26 },
  { kind: 'blob', sinceWave: 2, base: 10, perWave: 0.4, min: 0, max: 18 },
  { kind: 'crab', sinceWave: 2, base: 8, perWave: 0.4, min: 0, max: 16 },
  { kind: 'slime', sinceWave: 3, base: 8, perWave: 0.3, min: 0, max: 14 },
  { kind: 'creeper', sinceWave: 3, base: 7, perWave: 0.3, min: 0, max: 13 },
  { kind: 'rat', sinceWave: 4, base: 6, perWave: 0.3, min: 0, max: 12 },
]

export const MAPS = {
  meadow: {
    emoji: '1f33c',
    name: '草甸',
    desc: '一片开满野花的草甸。一边是黑压压的针叶林，林间小路被倒下的大树堵住了；一边是牧场的木栅栏，门闩着，羊在外头吃草；一边是一道陡坡，坡上是更高的一层草甸，上不去。这里没有别的规矩，放开手脚打就是',
    kind: 'meadow',
    stamina: { exertion: 0.4, regen: 1.2 },
    palette: {
      bgFrom: 'hsl(112 23% 42%)',
      bgTo: 'hsl(158 28% 17%)',
      map: hslToInt(107, 0.33, 0.56),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1f33c', '1fabb', '1f340'],
      sizeU: [0.3, 0.45],
      alpha: [0.8, 0.92],
      density: [0.012, 0.018],
    },
    mix: MEADOW_MIX,
    gates: {
      snapU: 4,
      fallback: 'rise',
      look: 'leaves',
      boss: 'brush',
      kinds: {
        woods: { name: '林间', at: { kind: 'nooks', spacingU: 6, away: { mark: 'bare', minU: 2 } }, enter: 'walk', look: 'leaves', weight: 3, perSec: 1.5, only: ['zombie', 'boar', 'slime', 'mushroom'] },
        brush: { name: '林缘', at: { kind: 'rim', segU: 3, away: { mark: 'bare', minU: 2.5 } }, enter: 'climb', look: 'leaves', weight: 1.5, perSec: 1, only: ['zombie', 'snake', 'rat', 'treant'] },
        log: { name: '倒木', at: { kind: 'mark' }, enter: 'climb', look: 'leaves', snapU: 5, weight: 3, perSec: 1, only: ['zombie', 'boar', 'slime', 'mushroom'] },
        fence: { name: '栅栏', at: { kind: 'mark' }, enter: 'climb', weight: 2, perSec: 1, only: ['zombie', 'locust', 'rat', 'snake'] },
        bank: { name: '坡顶', at: { kind: 'mark' }, enter: 'lob', look: 'leaves', reachU: 9, weight: 2, perSec: 1, only: ['locust', 'boar', 'zombie'] },
        swarm: { name: '蝗群', at: { kind: 'ground' }, enter: 'drop', look: 'leaves', weight: 2, only: ['locust'] },
        grass: { name: '草丛', at: { kind: 'ground' }, enter: 'rise', look: 'leaves', weight: 1 },
      },
    },
    finalWaveSub: '蛛后从林子里爬出来了——草地开阔，绕着它打！',
    meadow: {
      meterPerU: 0.5,
      sizeU: 36,
      areaU2: [760, 1040],
      neckU: 0.35,
      turf: { reliefM: 0.16, waveU: 7, riseM: 0.035 },
      bank: { insetU: [3.5, 6.5], bendU: 2.6, waveU: 12, spurs: [0, 2], spurU: [1.2, 3], spurWidthU: [2.5, 5], heightM: [3, 4], riseM: [0.8, 0.95] },
      forest: { insetU: [1.5, 5.5], bendU: 2.4, waveU: 9, scallopU: 0.45, lobes: [0, 2], lobeU: [1.5, 3.5], lobeWidthU: [1.6, 3], crownU: [1.3, 2.3], heightM: [4.5, 6.5], edgeU: [0.5, 1], birch: 0.25, overhangU: 0.4 },
      trail: { notchU: 1.6, widthU: 1.3, logU: [5, 6.5] },
      fence: { insetU: [1.5, 3], skewDeg: 6, kinkDeg: 6, postU: 2.6, heightM: 1.1, gateU: 2.2, farChance: 0.35 },
      flowers: { cover: 0.24, patchU: 4 },
      sheep: [3, 6],
    },
    boss: 'treant',
  },
  sakura: {
    emoji: '1f338',
    name: '樱庭',
    desc: '寺院外溪边的一片樱林空地，花开得正好，地上铺满了落花。一面是寺院的瓦顶土墙，另外三面是樱树林，林缘的樱树一棵挨一棵，走不进去。一条溪斜斜地穿过空地：上游从林子里一排大石头的缝里涌进来，下游漫过一道低石槛、穿过竹栅流进林子。溪水深：站不住的地方就顺水漂，只能划水往两边挣，逆流基本划不动；漂到下游就被水压在竹栅前，贴着竹栅挪到岸边才上得来——敌我都一样，落进水里的金币也堆在栅前。溪上有一座木桥，走桥上不沾水，桥下照样漂。巨鳄个子大，蹚得过去',
    kind: 'sakura',
    stamina: { exertion: 0.5, regen: 1 },
    palette: {
      bgFrom: 'hsl(350 38% 42%)',
      bgTo: 'hsl(22 34% 15%)',
      map: hslToInt(88, 0.32, 0.42),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1f338'],
      sizeU: [0.26, 0.38],
      alpha: [0.85, 0.95],
      density: [0.004, 0.008],
    },
    mix: RIVER_MIX,
    gates: {
      snapU: 3,
      fallback: 'rise',
      look: 'petals',
      boss: 'rocks',
      kinds: {
        grove: { name: '樱林', at: { kind: 'nooks', spacingU: 7, away: { mark: 'ports', minU: 2.5 } }, enter: 'walk', look: 'petals', weight: 3, perSec: 1.5, only: ['zombie', 'ghost', 'blob', 'slime', 'snake'] },
        thicket: { name: '林缘', at: { kind: 'rim', segU: 3, away: { mark: 'ports', minU: 2.5 } }, enter: 'climb', look: 'petals', weight: 1.5, perSec: 1, only: ['zombie', 'blob', 'slime', 'snake'] },
        wall: { name: '寺墙', at: { kind: 'mark' }, enter: 'climb', weight: 2, perSec: 1, only: ['ghost', 'zombie'] },
        bank: { name: '溪岸', at: { kind: 'mark' }, enter: 'climb', look: 'splash', weight: 3, perSec: 1.5, only: ['snake', 'puffer', 'turtle', 'siren', 'crab'] },
        rocks: { name: '石组', at: { kind: 'mark' }, enter: 'climb', look: 'splash', weight: 1, only: ['croc'] },
        lawn: { name: '落花', at: { kind: 'ground' }, enter: 'rise', look: 'petals', weight: 1 },
      },
    },
    finalWaveSub: '巨鳄顺着溪游了下来——别跟它在深水里纠缠！',
    sakura: {
      meterPerU: 0.5,
      cellU: 0.25,
      sizeU: 40,
      areaU2: [900, 1200],
      neckU: 0.35,
      wall: { insetU: [2.2, 3.2], skewDeg: 5, kinkDeg: 5, thickU: 0.6, heightM: 1.6, eaveU: 0.55, gateU: 2.4 },
      forest: { insetU: [3, 6], bendU: 2.2, waveU: 9, scallopU: 0.45, lobes: [0, 2], lobeU: [1.5, 3], lobeWidthU: [1.6, 3] },
      stream: { slantDeg: 25, turnDeg: 15, meanderU: 3.6, minBend: 1.6, wallGapU: 3 },
      flow: { discharge: 4, widthCoef: 1.55, depthCoef: 0.69, manning: 0.035, bedShape: 8, pool: 1.35, riffle: 0.8, thalwegShift: 0.35, bankM: 0.45, bankU: 1, floodSlope: 0.015, reliefM: 0.1 },
      rocks: { radiusU: [0.36, 0.82], gapU: [0.04, 0.2], heightM: 0.6 },
      sill: { rampU: 1.5, dropM: 0.8, postU: 0.42, heightM: 1.1 },
      bridge: { widthU: 2.6, rampU: 1.4, riseM: 0.6, at: [0.3, 0.7] },
      trees: { inside: [3, 6], crownU: [1.3, 2.2], heightM: [4, 6], overhangU: 0.5, templeGapU: 4.5 },
      body: { kg: 60, radiusU: 0.45, heightM: 1.7, density: 985, drag: 1.1, legs: 0.55, hip: 0.5, lever: 0.15, mu: 0.5, swim: 0.4, wetM: 0.02 },
    },
    boss: 'croc',
  },
  forest: {
    emoji: '1f332',
    name: '黑森林',
    desc: '苍郁密林，落叶与蕨草铺满林间空地',
    kind: 'bounded',
    stamina: { exertion: 0.4, regen: 1.2 },
    palette: {
      bgFrom: 'hsl(150 30% 30%)',
      bgTo: 'hsl(170 32% 17%)',
      map: hslToInt(110, 0.3, 0.7),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1f332', '1f333', '1f33f', '1f342', '1f343', '1faa8'],
      sizeU: [0.35, 0.95],
      alpha: [0.14, 0.26],
      density: [0.1, 0.14],
    },
    mix: FOREST_MIX,
    boss: 'treant',
  },
  oldDesert: {
    emoji: '1f3dc',
    name: '旧荒漠',
    desc: '烈日炙烤的荒漠，赶路格外耗体力，歇着也回得慢；沙丘与枯骨之间潜伏着不知疲倦的毒物',
    kind: 'bounded',
    size: { w: 30, h: 30 },
    stamina: { exertion: 1.5, regen: 0.7 },
    palette: {
      bgFrom: 'hsl(30 42% 36%)',
      bgTo: 'hsl(15 38% 20%)',
      map: hslToInt(45, 0.48, 0.76),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1f335', '1faa8', '1f9b4', '1f480', '1f940'],
      sizeU: [0.35, 0.9],
      alpha: [0.14, 0.26],
      density: [0.08, 0.11],
    },
    mix: DESERT_MIX,
    finalWaveSub: '蝎王不知疲倦，你会累——别在流沙里挣扎！',
    boss: 'scorpion',
  },
  oldRiver: {
    emoji: '1f30a',
    name: '奔流（旧）',
    desc: '一条永不停歇的大河，万物皆随波逐流；两岸静看你逆流而战',
    kind: 'oldRiver',
    stamina: { exertion: 0.5, regen: 1 },
    palette: {
      bgFrom: 'hsl(28 32% 30%)',
      bgTo: 'hsl(205 38% 15%)',
      map: hslToInt(197, 0.52, 0.66),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1f33e', '1f33f', '1faa8', '1f333', '1f344'],
      sizeU: [0.4, 0.8],
      alpha: [0.3, 0.45],
      density: [0.1, 0.14],
    },
    drift: ['1f343', '1f338', '1fae7', '1f342'],
    mix: RIVER_MIX,
    finalWaveSub: '大河没有退路，正面迎战！',
    oldRiver: {
      viewScale: 1.2,
      width: 12,
      flow: 1,
      upstream: 2.4,
      downstream: 0.3,
      coinCullPad: 2,
      enemyCullPad: 6,
      driftCount: 18,
      driftSpeedMul: [0.75, 1.3],
      waveSlow: 0.6,
      waveFast: 1.2,
    },
    boss: 'croc',
  },
  void: {
    emoji: '1f3ed',
    name: '工厂',
    desc: '轰鸣的自动化车间，四壁皆是传送闸口——出这头即现那头',
    kind: 'void',
    stamina: { exertion: 0.35, regen: 1 },
    palette: {
      bgFrom: 'hsl(210 16% 20%)',
      bgTo: 'hsl(214 22% 8%)',
      map: hslToInt(210, 0.08, 0.34),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['2699', '1f527', '1f529', '1f6e2', '1f4e6', '1f6e0'],
      sizeU: [0.3, 0.7],
      alpha: [0.14, 0.26],
      density: [0.05, 0.09],
    },
    mix: FACTORY_MIX,
    finalWaveSub: '环形厂区无处可退，正面迎战！',
    torus: {
      arenaLong: 24,
      arenaShort: 13.5,
      projectileLifeMs: 1500,
      frame: 0.3,
    },
    boss: 'mecha',
  },
  oldRuins: {
    emoji: '1f3da',
    name: '残垣（旧）',
    desc: '断壁残垣的废墟回廊——墙挡人、挡弹、也挡视线，墙后的敌人只剩淡影；靠掩体、卡口与探头作战',
    kind: 'oldRuins',
    stamina: { exertion: 0.6, regen: 1 },
    palette: {
      bgFrom: 'hsl(35 16% 28%)',
      bgTo: 'hsl(28 18% 12%)',
      map: hslToInt(38, 0.12, 0.62),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1faa8', '1f9f1', '1f940', '1f33f'],
      sizeU: [0.3, 0.7],
      alpha: [0.12, 0.22],
      density: [0.05, 0.08],
    },
    mix: RUINS_MIX,
    walls: { blocks: 15, maxLen: 4, centerClearU: 3.5, spawnMinCellDist: 5, reflowMs: 120, bodyRadiusCapU: 0.45 },
    boss: 'rhino',
  },
  ruins: {
    emoji: '1f3da',
    name: '残垣',
    desc: '山顶台地上一座塌了大半的石砌院落：中间是柱廊围着的回廊院，四周一圈房间，一角是塔楼。墙剩多高就挡多少——高过膝盖挡人，高过胸口挡子弹，高过眼睛挡视线，看不见的敌人不会被自动瞄准，只剩一道淡影；跨得过的残基贴着地面，挡路的墙露出一截立面，越高露得越多。矮墙后能探头开火，封门的木板挡人也挡视线，只有能穿透的子弹打得过去。冲锋的暴龙、自爆的怪和几种技能能把墙打出缺口，失去支撑的部分整片塌下来：落石砸人，墙脚堆起拖慢脚步的碎石，扬起的尘雾一时看不穿。怪物从你看不见的地方摸过来',
    kind: 'ruins',
    stamina: { exertion: 0.5, regen: 1 },
    palette: {
      bgFrom: 'hsl(30 30% 22%)',
      bgTo: 'hsl(24 32% 8%)',
      map: hslToInt(40, 0.2, 0.42),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1f33c', '1f344', '1f33f'],
      sizeU: [0.3, 0.5],
      alpha: [0.75, 0.9],
      density: [0.006, 0.01],
    },
    mix: RUINS_MIX,
    gates: {
      snapU: 3,
      fallback: 'rise',
      boss: 'slope',
      kinds: {
        door: { name: '院门', at: { kind: 'mark' }, enter: 'walk', weight: 3, perSec: 1.5 },
        slope: { name: '山坡', at: { kind: 'rim', segU: 3 }, enter: 'climb', look: 'leaves', weight: 2, perSec: 1 },
        wall: { name: '断墙', at: { kind: 'mark' }, enter: 'climb', weight: 1.5, perSec: 1, only: ['zombie', 'skeleton', 'snake', 'knight', 'gargoyle'] },
        haunt: { name: '墙里', at: { kind: 'mark' }, enter: 'walk', look: 'steam', weight: 3, perSec: 1, only: ['ghost'] },
      },
    },
    finalWaveSub: '暴龙撞穿墙冲过来——别和它一起被塌下的墙堵在屋里！',
    ruins: {
      meterPerU: 0.5,
      cellU: 0.25,
      site: { marginU: [2.6, 4.8], waveU: 7, padU: 2.5, neckU: 0.8 },
      plan: {
        tiltDeg: [8, 24],
        garthU: [6, 8],
        walkU: 3.2,
        depthU: [6.5, 8],
        roomU: [6, 10],
        doorU: [2.4, 3],
        gates: [2, 4],
        loops: 0.3,
        wallU: { outer: 1.5, inner: 1, tower: 1.75, parapet: 0.75 },
      },
      masonry: { courseM: 0.28, density: 2200, bond: 2, heightM: { outer: [4.2, 5.6], inner: [3, 4.2], tower: [7, 9], parapet: 0.84, column: 3.4 } },
      arcade: { radiusU: 0.4, spacingU: 2.9, entries: [1, 1] },
      decay: { waveU: 6, keep: [0.1, 1], razed: [2, 4], razeU: [1.6, 3], breaches: [2, 4], breachM3: [0.6, 1.6], broken: 0.35, fallen: 0.2, rubble: 0.06 },
      timber: { doors: [1, 3], heightM: 1.9, thickU: 0.3 },
      rubble: { reposeDeg: 36, fullM: 0.4, viscosity: 1.6, exertion: 0.5 },
      fall: { damagePerKJ: 8, radiusU: 0.35 },
      dust: { perM3: 6, spreadU: 2.5, halfLifeS: 2.5, opaqueTau: 1.2 },
      trees: { crownU: [1.3, 2.4], heightM: [6, 11], gapU: 2.6 },
      bodyCapU: 0.8,
      gapU: 2,
      reflowMs: 150,
    },
    boss: 'rhino',
  },
  daynight: {
    emoji: '1f304',
    name: '晨昏原野',
    desc: '随昼夜轮转的旷野：正午视野纵览全场，午夜相机收窄、四合起以身为心的迷雾；昼夜各出一批怪',
    kind: 'daynight',
    size: { w: 30, h: 30 },
    stamina: { exertion: 0.4, regen: 1 },
    palette: {
      bgFrom: 'hsl(245 30% 28%)',
      bgTo: 'hsl(258 34% 11%)',
      map: hslToInt(150, 0.2, 0.6),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1f33e', '1f33f', '1f33b', '1f33c', '1faa8'],
      sizeU: [0.35, 0.9],
      alpha: [0.14, 0.26],
      density: [0.09, 0.13],
    },
    mix: [...DAY_MIX, ...NIGHT_MIX],
    dayMix: DAY_MIX,
    nightMix: NIGHT_MIX,
    dayNight: {
      cycleSec: 48,
      startHour: 6,
      visionMax: 30,
      visionMid: 20,
      visionMin: 10,
      fogRadiusDusk: 11,
      fogRadiusMidnight: 3.5,
      fogAlphaMax: 0.9,
      daySpawnScale: 0.68,
      nightSpawnScale: 1.55,
    },
    finalWaveSub: '击败它，或撑过头目波——注意昼夜轮替，夜幕里它更难缠！',
    boss: 'eclipse',
  },
  space: {
    emoji: '1f30c',
    name: '深空',
    desc: '被黑洞禁锢的圆形星域——全程困在一个圈里，越靠边缘引力越强、谁也逃不出去；天体不时拖着直线横扫战场（敌我通吃），终波奇点正面决战',
    kind: 'space',
    stamina: { exertion: 0.3, regen: 0.8 },
    palette: {
      bgFrom: 'hsl(245 45% 14%)',
      bgTo: 'hsl(255 55% 4%)',
      map: hslToInt(246, 0.45, 0.09),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['2b50', '2728', '1f31f', '1f4ab'],
      sizeU: [0.3, 0.7],
      alpha: [0.16, 0.32],
      density: [0.06, 0.1],
    },
    mix: SPACE_MIX,
    finalWaveSub: '奇点降临——禁锢星域内已无处可逃，正面迎战！',
    space: {
      blackholeRadiusU: 12.5,
      meteor: {
        intervalMs: 15000,
        intervalJitterMs: 5000,
        warnMs: 1500,
        radiusU: 2.6,
        speedU: 14,
        travelU: 30,
        offsetU: 7,
        damage: 30,
      },
    },
    boss: 'blackhole',
  },
  ice: {
    emoji: '2744',
    name: '旧浮冰',
    desc: '脚下是打滑的浮冰——不跟手、刹不住、会过冲；四周刺骨寒水，滑出冰面就掉血、越游越慢（敌我通吃）。低摩擦让击退格外突出，把敌人推下水淹死是这里的活路',
    kind: 'ice',
    stamina: { exertion: 0.3, regen: 0.9 },
    palette: {
      bgFrom: 'hsl(205 45% 20%)',
      bgTo: 'hsl(215 55% 6%)',
      map: hslToInt(198, 0.32, 0.82),
      shadow: 0x0a1f33,
    },
    decor: {
      emojis: ['2744', '1f9ca'],
      sizeU: [0.3, 0.7],
      alpha: [0.14, 0.28],
      density: [0.05, 0.09],
    },
    mix: ICE_MIX,
    ice: {
      floeU: 25,
      traction: 0.12,
      waterTraction: 0.35,
      waterViscosity: 2.5,
      waterExertion: 2.5,
      waterRegen: 0.3,
      waterTeamDps: 16,
      waterEnemyDps: 32,
      waterTickMs: 250,
    },
    boss: 'swan',
  },
  nebulaOld: {
    emoji: '1f573',
    name: '旧星云',
    desc: '一团空心的星云，空腔里某处藏着一个黑洞：人、怪、子弹、流星、掉落物都受它的万有引力，越近越强，中心掉进视界就被吞噬；空腔外是厚重的星云壳层，越往外走被它拉回得越狠，谁也出不去；壳层里落下的碎块化作流星横穿空腔',
    kind: 'nebulaOld',
    stamina: { exertion: 0.3, regen: 0.8 },
    palette: {
      bgFrom: 'hsl(290 45% 17%)',
      bgTo: 'hsl(255 55% 5%)',
      map: hslToInt(270, 0.45, 0.08),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['2b50', '2728', '1f31f', '1f4ab'],
      sizeU: [0.3, 0.7],
      alpha: [0.16, 0.32],
      density: [0.05, 0.08],
    },
    mix: SPACE_MIX,
    finalWaveSub: '奇点降临——别被它逼进黑洞的视界！',
    nebulaOld: {
      shell: { innerU: 18, outerU: 30, gm: 120_000 },
      contain: { speedMul: 1.5, leapU: 8 },
      hole: { gm: 110, softeningU: 0.6, horizonU: 1.2, fromCenterU: [8, 12], clearU: 5 },
      meteor: {
        firstMs: 7000,
        intervalMs: 15000,
        intervalJitterMs: 5000,
        warnMs: 1800,
        radiusU: 1.3,
        speedU: 12,
        offsetU: 6,
        damage: 30,
        stepMs: 16,
        maxFlightMs: 5000,
      },
    },
    boss: 'blackhole',
  },
  volcano: {
    emoji: '1f30b',
    name: '火山',
    desc: '四周崖壁环绕的熔岩盆地，一座活火山背靠盆地边，陡峭的山体谁也上不去。它定期喷发：先冒烟发红、地动山摇，随后熔岩漫过火山口，往四面八方顺着地势流下来。熔岩盖住的地方敌我都受伤；离火山口越远凉得越快，凝成黑色的岩石后又能站人',
    kind: 'volcano',
    size: { w: 32, h: 32 },
    stamina: { exertion: 0.5, regen: 0.9 },
    palette: {
      bgFrom: 'hsl(210 6% 19%)',
      bgTo: 'hsl(210 20% 6%)',
      map: hslToInt(209, 0.05, 0.3),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1faa8', '1f9b4', '1f480'],
      sizeU: [0.3, 0.8],
      alpha: [0.2, 0.34],
      density: [0.03, 0.05],
    },
    mix: VOLCANO_MIX,
    // 崖脚的洞里走出来、崖顶跳下来、喷气孔里钻出来、喷发时火山口抛出来、骷髅从灰里爬起来；暴龙从山坡上下来
    gates: {
      snapU: 3,
      fallback: 'rise',
      boss: 'foot',
      kinds: {
        cave: { name: '洞穴', at: { kind: 'nooks', spacingU: 6, away: { mark: 'cone', minU: 9 } }, enter: 'walk', snapU: 5, weight: 3, perSec: 1.5, only: ['zombie', 'boar', 'creeper', 'skeleton'] },
        cliff: { name: '崖顶', at: { kind: 'rim', segU: 3, away: { mark: 'cone', minU: 9 } }, enter: 'climb', snapU: 5, weight: 1.5, perSec: 1, only: ['gargoyle', 'zombie'] },
        vent: { name: '喷气孔', at: { kind: 'mark' }, enter: 'rise', look: 'steam', weight: 2, perSec: 1, only: ['turtle', 'creeper'] },
        crater: { name: '火山口', at: { kind: 'mark' }, enter: 'lob', look: 'sparks', weight: 4, perSec: 4, reachU: 14, only: ['comet', 'turtle'] },
        ash: { name: '灰地', at: { kind: 'ground' }, enter: 'rise', weight: 1 },
        foot: { name: '山坡', at: { kind: 'mark' }, enter: 'walk', weight: 1, only: ['rhino'] },
      },
    },
    finalWaveSub: '暴龙踏着熔岩而来——别在火山脚下恋战！',
    volcano: {
      cellU: 0.5,
      rim: { insetU: [0.5, 2.5], waveU: 7, cornerU: 5, neckU: 1, cliffU: 1.1, cliffHeight: 2.6, backSlope: 0.12 },
      cone: { insetU: [0.5, 1.5], craterU: 1.6, blockU: 4, blockJitter: 0.1, height: 4, footHeight: 0.9, radiusU: 9, craterDepth: 1.4, lakeDepth: 0.8, gullyDepth: 0.45 },
      terrain: { tilt: 0.2, relief: 1.2, waveU: 7 },
      eruption: {
        firstMs: 15000,
        intervalMs: 60000,
        intervalJitterMs: 6000,
        warnMs: 5000,
        rate: 5,
        peakMs: 1200,
        waneMs: 8000,
        effuseMs: 30000,
        lobes: [4, 6],
        lobeSpreadDeg: 110,
        lobeDeg: 16,
        lobeFloor: 0.08,
        history: 2,
      },
      lava: {
        stepMs: 100,
        mobility: 40,
        mobilityPow: 2,
        yieldHot: 0.015,
        yieldCold: 0.1,
        cooling: 0.012,
        coolRadiusU: 6,
        solidus: 0.3,
        teamDps: 30,
        enemyDps: 45,
        tickMs: 250,
      },
    },
    boss: 'rhino',
  },
  ship: {
    emoji: '26f5',
    name: '帆船',
    desc: '一艘在海上航行的三桅帆船，舷墙围着的甲板就是战场。甲板上的一切都有重量：人群挤到哪边，船就往哪边倾，海浪也推着它来回摇。船一倾，往高处走就吃力变慢、往低处走更快；站着不动会顺着甲板往低处滑，金币也跟着溜，散落的炮弹满甲板滚——别被怪物堵在低的那一侧',
    kind: 'ship',
    stamina: { exertion: 0.5, regen: 1 },
    palette: {
      bgFrom: 'hsl(180 58% 29%)',
      bgTo: 'hsl(182 80% 12%)',
      map: hslToInt(32, 0.27, 0.63),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1faa2', '1faa3', '1f9ed'],
      sizeU: [0.5, 0.8],
      alpha: [0.8, 0.95],
      density: [0.006, 0.009],
    },
    mix: SHIP_MIX,
    // 舱底的从舱口与天窗爬上来、海里的翻过舷墙登船（船往哪边倾，低的那一舷来得多）、幽灵从索具上落下；巨鳄也翻舷墙上来
    gates: {
      snapU: 3,
      fallback: 'drop',
      boss: 'rail',
      lean: { mul: 4, full: 4 },
      kinds: {
        hatch: { name: '舱口', at: { kind: 'mark' }, enter: 'rise', weight: 3, perSec: 2.5, only: ['zombie', 'skeleton', 'rat', 'raccoon', 'creeper'] },
        skylight: { name: '天窗', at: { kind: 'mark' }, enter: 'rise', weight: 2, perSec: 1, only: ['ghost', 'rat'] },
        rail: { name: '舷墙', at: { kind: 'rim', segU: 3 }, enter: 'climb', look: 'splash', weight: 2, perSec: 1, only: ['zombie', 'skeleton', 'puffer', 'siren', 'croc'] },
        rigging: { name: '索具', at: { kind: 'ground' }, enter: 'drop', weight: 1, only: ['ghost'] },
      },
    },
    finalWaveSub: '巨鳄爬上了甲板——它有一吨重，它往哪边走，船就往哪边倾！',
    ship: {
      meterPerU: 0.45,
      hull: { lengthU: 48, beamU: 18, bow: 0.42, bowPow: 0.85, stern: 0.2, sternPow: 2.5, transom: 0.62, transomBulge: 0.05, bulwarkU: 0.45, seaU: 5, neckU: 0.6, masts: [0.22, 0.5, 0.76], mastU: 0.45 },
      hydro: { draftM: 2, midship: 0.78, kgM: 2.5, depthM: 4.2, rho: 1025, rollGyration: 0.38, pitchGyration: 0.26, rollAdded: 0.2, pitchAdded: 0.8, rollDamping: 0.15, pitchDamping: 0.35 },
      weight: { bodyKg: 75, bodyRadiusU: 0.45, bodyHeightM: 0.9, pickupKg: 0.05, ballKg: 14.5 },
      sea: {
        speedMs: 1.2,
        swells: [
          { heightM: 0.8, periodS: 8, towardDeg: 80 },
          { heightM: 0.2, periodS: 5.5, towardDeg: 160 },
          { heightM: 0.6, periodS: 11, towardDeg: 40 },
        ],
      },
      friction: { body: { static: 0.08, kinetic: 0.06 }, coin: { static: 0.04, kinetic: 0.03 }, ballRolling: 0.005 },
      gait: { flatResistance: 1.5, downhillMax: 1.3, effortMin: 0.4 },
      balls: { count: 6, radiusU: 0.18, restitution: 0.35 },
    },
    boss: 'croc',
  },
  floe: {
    emoji: '2744',
    name: '浮冰',
    desc: '南极海上漂着的一块浮冰，四面都是冰点上下的海水。积雪的地方踩得住，裸露的老冰和裂缝冻成的新冰滑得站不稳——走不跟手、刹不住，挨一下能滑出老远；滑出冰缘就掉进海里，冷水几秒就把人冻僵（敌我通吃）。海风一阵阵刮过来，阵风大时新冰上站不住，个子小的在光冰上也会被吹着滑',
    kind: 'floe',
    stamina: { exertion: 0.3, regen: 0.9 },
    palette: {
      bgFrom: 'hsl(202 38% 24%)',
      bgTo: 'hsl(214 48% 7%)',
      map: hslToInt(200, 0.22, 0.86),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['2744', '1f9ca'],
      sizeU: [0.3, 0.7],
      alpha: [0.14, 0.28],
      density: [0.05, 0.09],
    },
    mix: ICE_MIX,
    gates: {
      snapU: 4,
      fallback: 'rise',
      look: 'snow',
      boss: 'sky',
      lean: { mul: 3, full: 13 },
      kinds: {
        edge: { name: '冰缘', at: { kind: 'rim', segU: 3 }, enter: 'climb', look: 'splash', snapU: 8, weight: 3, perSec: 1.5, only: ['zombie', 'turtle', 'crab', 'snake', 'blob'] },
        seam: { name: '新冰缝', at: { kind: 'mark' }, enter: 'rise', look: 'splash', weight: 2, perSec: 1, only: ['turtle', 'crab', 'snake'] },
        drift: { name: '雪堆', at: { kind: 'mark' }, enter: 'rise', look: 'snow', weight: 2, perSec: 1.5, only: ['zombie', 'boar', 'blob', 'creeper', 'knight'] },
        squall: { name: '风雪', at: { kind: 'ground' }, enter: 'drop', look: 'snow', weight: 1.5, only: ['ghost'] },
        sky: { name: '天上', at: { kind: 'ground' }, enter: 'drop', look: 'snow', weight: 1, only: ['swan'] },
      },
    },
    floe: {
      meterPerU: 0.4,
      frameU: 52,
      cellU: 0.125,
      shape: {
        areaU: 1024,
        turnDeg: 8,
        sideDeg: 6,
        sideU: 1.5,
        cutChance: 0.55,
        cutU: [1.5, 5],
        bendU: 0.9,
        bites: [1, 2],
        biteDepthU: [2.5, 5],
        biteWidthU: [4, 8],
        leadChance: 0.6,
        leadU: [5, 9],
        leadWidthU: [1.2, 1.9],
        seamWidthU: [0.9, 1.6],
        jagU: 0.22,
        roundU: [0.8, 2.2],
      },
      ice: { thicknessM: 1.6, youngM: 0.25, density: 917, seaDensity: 1027 },
      snow: { maxM: 0.18, cover: 0.5, density: 330, waveU: 3.5, bareU: 1.6 },
      friction: { snow: { static: 0.55, kinetic: 0.42 }, ice: { static: 0.22, kinetic: 0.16 }, young: { static: 0.11, kinetic: 0.07 }, loose: 0.12 },
      body: { footFrac: 0.6, swimRatio: 0.3, refRadiusU: 0.45, dragU: 1, freezeSec: 8, climbFrac: 0.5 },
      wind: {
        meanMs: 7,
        gustMs: 13,
        firstMs: 20000,
        intervalMs: 36000,
        jitterMs: 8000,
        riseMs: 2500,
        holdMs: 3500,
        fallMs: 3000,
        veerDeg: 15,
        airDensity: 1.34,
        dragArea: 0.012,
        driftRatio: 0.02,
        driftDeg: 30,
        fetchM: 150,
      },
      waterExertion: 1.5,
      waterRegen: 0.2,
      coldTickMs: 250,
    },
    boss: 'swan',
  },
  nebula: {
    emoji: '1f30c',
    name: '星云',
    desc: '深空里一团空心的星云，空腔里藏着一个黑洞。这里没有太阳，光来自黑洞吸积盘和偶尔划过的流星。人、怪、金币、子弹和流星都受万有引力：身体被拖着漂，子弹和流星的轨迹被引弯；黑洞周围那圈被弯过来的光就是走不出来的地方，掉进视界就被吞掉，吞下的东西让黑洞越长越大。空腔外是厚厚的星云壳层，往里走得越深被拉回得越狠，谁也出不去',
    kind: 'nebula',
    stamina: { exertion: 0.4, regen: 0.9 },
    palette: {
      bgFrom: 'hsl(330 38% 16%)',
      bgTo: 'hsl(290 34% 5%)',
      map: hslToInt(330, 0.34, 0.16),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['2728'],
      sizeU: [0.3, 0.5],
      alpha: [0, 0],
      density: [0, 0],
    },
    mix: NEBULA_MIX,
    gates: {
      snapU: 3,
      fallback: 'rise',
      look: 'glow',
      boss: 'horizon',
      kinds: {
        shell: { name: '壳层', at: { kind: 'rim', segU: 3, away: { mark: 'hole', minU: 10 } }, enter: 'climb', look: 'glow', weight: 3, perSec: 1.5, only: ['zombie', 'alien', 'chameleon', 'siren', 'ghost'] },
        sky: { name: '上空', at: { kind: 'ground' }, enter: 'drop', look: 'glow', weight: 1.5, only: ['ufo', 'siren'] },
        meteor: { name: '流星', at: { kind: 'mark' }, enter: 'lob', look: 'sparks', weight: 4, perSec: 3, reachU: 20, only: ['comet'] },
        horizon: { name: '视界边', at: { kind: 'mark' }, enter: 'walk', look: 'glow', weight: 1, only: ['blackhole'] },
        dust: { name: '星尘', at: { kind: 'ground' }, enter: 'rise', look: 'glow', weight: 1 },
      },
    },
    finalWaveSub: '奇点从视界边上走来——别被它和黑洞夹在中间！',
    nebula: {
      shell: { innerU: 18, outerU: 26, gm: 3_000_000, rise: 1.5, tau: 90 },
      contain: { speedMul: 1.5, depthU: 2, leapU: 8 },
      hole: { gm: 360, maxGm: 560, lightU: 33, fromCenterU: [6, 9], startU: 7 },
      swallow: { bodyGm: 4, bodyRadiusU: 0.45, pickupGm: 0.05, shotGm: 0.02, lightEta: 1 / 256 },
      accretion: { bondiGm: 0.05, riseMs: 200, viscousMs: 2500 },
      disk: { outerRs: 4.5, innerK: 2800 },
      meteor: {
        firstMs: 9000,
        intervalMs: 16000,
        intervalJitterMs: 5000,
        warnMs: 1800,
        speedU: 11,
        speedJitter: 0.15,
        radiusU: 0.85,
        shatterU: 1.2,
        offsetU: 5,
        damage: 24,
        gm: 6,
        maxFlightMs: 7000,
      },
      spawnClearU: 1.5,
      cameraU: 40,
    },
    boss: 'blackhole',
  },
  cave: {
    emoji: '1f987',
    name: '溶洞',
    desc: '一座部分露天的石灰岩溶洞。阳光从洞顶的天窗照进来，随太阳东升西落：白天整个洞厅亮堂，看得到大半个洞；黄昏光柱变红、爬上洞壁，洞里一点点暗下来；入夜后只看得清火把照亮的那一圈。怪物只从暗处出来：白天从深处的支洞里，夜里可能就在火光外不远处。石柱与大石笋挡人也挡子弹，被它们挡住的敌人只剩淡影，水潭里蹚水更慢',
    kind: 'cave',
    size: { w: 36, h: 36 },
    stamina: { exertion: 0.5, regen: 1 },
    palette: {
      bgFrom: 'hsl(30 28% 13%)',
      bgTo: 'hsl(22 34% 5%)',
      map: hslToInt(34, 0.24, 0.34),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1f9b4', '1f578', '26cf'],
      sizeU: [0.35, 0.7],
      alpha: [0.55, 0.8],
      density: [0.03, 0.05],
    },
    mix: CAVE_MIX,
    gates: {
      snapU: 3,
      fallback: 'rise',
      boss: 'main',
      kinds: {
        alcove: { name: '支洞', at: { kind: 'mark' }, enter: 'walk', weight: 3, perSec: 1.5 },
        crack: { name: '石缝', at: { kind: 'nooks', spacingU: 6, away: { mark: 'tunnel', minU: 2.5 } }, enter: 'walk', weight: 2, perSec: 1, only: ['rat', 'slime', 'creeper', 'zombie', 'skeleton'] },
        pool: { name: '水潭', at: { kind: 'mark' }, enter: 'rise', look: 'splash', weight: 2, perSec: 1, only: ['slime', 'siren'] },
        glow: { name: '荧光丛', at: { kind: 'mark' }, enter: 'rise', look: 'glow', weight: 2, perSec: 1, only: ['mushroom', 'slime'] },
        skylight: { name: '天窗', at: { kind: 'mark' }, enter: 'drop', weight: 1.5, perSec: 1, only: ['gargoyle', 'zombie', 'skeleton'] },
        main: { name: '主天窗', at: { kind: 'mark' }, enter: 'drop', weight: 1, only: ['eclipse'] },
        dark: { name: '暗处', at: { kind: 'ground' }, enter: 'rise', weight: 1 },
      },
    },
    finalWaveSub: '夜伯爵从黑暗里来——守住火光！',
    cave: {
      hall: { insetU: [2.5, 5.5], waveU: 8, cornerU: 6, neckU: 0.8, ceilingM: 10, wallU: 2.2 },
      skylights: { mainCount: [2, 2], mainU: [3.6, 4.4], mainOffsetU: [1, 3.5], minorCount: [2, 3], minorU: [1.4, 2.2], jitter: 0.22, gapU: 3, rubbleM: 1.4, rubbleSpread: 1.25 },
      alcoves: { count: [4, 4], widthU: 2.6, outU: 2.6, alongU: [3.5, 5.5], pocketU: 1.5 },
      formations: { columns: [7, 11], columnU: [0.55, 0.95], stalagmites: [48, 66], clusters: [7, 8], stalagmiteU: [0.16, 0.6], stalagmiteM: [0.6, 2.8], blockU: 0.32, clearU: 4 },
      pools: { count: [5, 8], sizeU: [1.6, 3.2], viscosity: 1.35, exertion: 1.2 },
      sky: { latitudeDeg: 24, declinationDeg: 6, dayS: 108, startHour: 9.5, extinction: 0.21, dwell: 10, dwellCenterDeg: -2.5, dwellWidthDeg: 4 },
      light: { albedo: 0.42, bounceU: 5, glowCount: [8, 15], glowLux: 0.4 },
      torch: { candela: 110, heightM: 1.4, igniteLux: 15, douseLux: 40, staggerMs: 1400 },
      view: { dayU: 18, nightU: 7, darkLux: 0.5, brightLux: 30, clearLux: 2 },
      spawnLux: 1,
    },
    boss: 'eclipse',
  },
  desert: {
    emoji: '1f3dc',
    name: '沙漠',
    desc: '一片走不出去的沙海：一直朝一个方向走，会从另一头绕回来，看到的还是那几座沙丘、那几样标志、那一群怪；沙丘和标志还都是一对一对的，分不清是回到了原地还是到了另一处。松沙上赶路、爬沙丘格外耗体力，丘间实一点的沙和踩实的脚印省力些，背阴处歇得回得快；走过的地方留下脚印，越累印子越深，见底时拖着脚走；脚印过一会儿就被风吹平',
    kind: 'desert',
    size: { w: 32, h: 32 },
    stamina: { exertion: 0.75, regen: 0.55 },
    palette: {
      bgFrom: 'hsl(35 43% 54%)',
      bgTo: 'hsl(22 32% 20%)',
      map: hslToInt(42, 0.84, 0.69),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['1f9b4'],
      sizeU: [0.3, 0.5],
      alpha: [0.75, 0.9],
      density: [0.002, 0.0035],
    },
    mix: DESERT_MIX,
    gates: {
      snapU: 3,
      fallback: 'rise',
      look: 'sand',
      boss: 'burrow',
      kinds: {
        crest: { name: '丘顶', at: { kind: 'mark' }, enter: 'climb', look: 'sand', weight: 2, perSec: 1 },
        marker: { name: '标志物', at: { kind: 'mark' }, enter: 'walk', look: 'sand', snapU: 4, weight: 3, perSec: 1, only: ['snake', 'rat', 'turtle', 'skeleton'] },
        burrow: { name: '沙下', at: { kind: 'ground' }, enter: 'rise', look: 'sand', weight: 1 },
      },
    },
    finalWaveSub: '蝎王在沙下穿行——别在沙丘上耗光体力！',
    desert: {
      meterPerU: 0.5,
      viewMaxU: 26,
      sunDeg: 36,
      dunes: { pairs: [2, 3], heightM: [0.3, 0.6], lobes: [1, 3], stossSlope: 0.28, leeSlope: 0.48, width: 1, turnDeg: 25 },
      windSpreadDeg: 50,
      swell: { heightM: 0.15, waves: 3 },
      flats: { loose: [0.4, 0.7], patches: 4 },
      landmarks: { pairs: 3, gapU: 7 },
      gait: { softSand: 1.8, packRelief: 0.5, maxPower: 2.6, downhillMax: 1.25 },
      shadeRegen: 1.25,
      tracks: {
        perU: 32,
        depthM: 0.018,
        firm: 0.3,
        tired: 2.6,
        dragFrom: 0.25,
        stride: 0.85,
        foot: 0.62,
        lifeS: 10,
        pack: 0.12,
        gaits: { zombie: 'foot', skeleton: 'foot', boar: 'hoof', snake: 'slither', rat: 'paw', raccoon: 'paw', turtle: 'paw', creeper: 'paw', locust: 'hop', scorpion: 'legs' },
      },
    },
    boss: 'scorpion',
  },
  circuit: {
    emoji: '26a1',
    name: '电路板',
    desc: '一块电路板上屏蔽罩围着的一小片：队伍和敌人缩得比芯片还小，芯片像楼，走线像路，丝印字铺满地面。镀金的裸铜线带电，碰到就触电，敌我都一样：电源线一直通着；时钟线跟着指示灯一通一断，通电前先闪；踩一下触摸开关，连线和连着的铜板一齐通电一阵；芯片和罩壁之间的过道里，两根电极隔一阵蓄满电，打出一道电弧。阻焊层底下的暗线不带电',
    kind: 'circuit',
    stamina: { exertion: 0.4, regen: 1 },
    palette: {
      bgFrom: 'hsl(184 40% 16%)',
      bgTo: 'hsl(198 46% 5%)',
      map: hslToInt(178, 0.32, 0.15),
      shadow: 0x000000,
    },
    decor: {
      emojis: ['26a1'],
      sizeU: [0.3, 0.5],
      alpha: [0, 0],
      density: [0, 0],
    },
    mix: CIRCUIT_MIX,
    gates: {
      snapU: 3,
      fallback: 'rise',
      look: 'glow',
      boss: 'wall',
      kinds: {
        wall: { name: '罩壁', at: { kind: 'rim', segU: 3, away: { mark: 'gap', minU: 2.5 } }, enter: 'climb', snapU: 6, weight: 4, perSec: 1.5, only: ['zombie', 'invader', 'crab', 'creeper', 'rat', 'mecha'] },
        via: { name: '过孔', at: { kind: 'mark' }, enter: 'rise', look: 'glow', snapU: 4.5, weight: 1, perSec: 1, only: ['zombie', 'invader', 'blob', 'crab', 'slime', 'creeper', 'rat'] },
        chip: { name: '芯片底下', at: { kind: 'mark' }, enter: 'walk', look: 'steam', snapU: 5, weight: 4, perSec: 1, only: ['invader', 'rat', 'crab', 'creeper'] },
        board: { name: '板面', at: { kind: 'ground' }, enter: 'rise', look: 'glow', weight: 1 },
      },
    },
    finalWaveSub: '失控核心翻过屏蔽罩闯了进来——把它引到通电的铜线上！',
    circuit: {
      mmPerU: 1.4,
      sizeU: 36,
      areaU2: [800, 1000],
      neckU: 0.35,
      frame: { insetU: [1.4, 2], chamferU: [2.4, 4.8], heightMM: 1.6 },
      plazaU: 4.5,
      aisleU: [2.6, 3],
      chipU: [1.5, 2.5],
      shock: { teamDps: 30, enemyDps: 45, tickMs: 250, footFrac: 0.5 },
      rail: { widthU: [1.2, 1.5] },
      clock: { traces: [2, 3], widthU: 0.85, pitchU: 1.27, offMs: 2600, warnMs: 1100, onMs: 2200 },
      arc: { count: [2, 3], gapU: [1.8, 2.5], restMs: 1800, chargeMs: 3600, arcMs: 380, reachU: 0.45, teamDamage: 30, enemyDamage: 60 },
      button: { padU: 1, touchU: 0.55, plateU: [4.4, 5.6], reachU: [2.4, 3.6], holdMs: 3200, rearmMs: 4800 },
    },
    boss: 'mecha',
  },
} as const satisfies Record<string, MapDef>
