import type { StatusDef } from '../legacy/types/statuses'

const ALL = ['move', 'act', 'cast', 'dash'] as const

/** 状态表：身体上带时限的标记，能封住的动作、逼着做的事、折进属性的倍率、再上一次怎么并、底色与图标都写在这里 */
export const STATUSES = {
  slow: { name: '减速', desc: '移速乘上参数，越小越慢', cleansable: true, stat: { key: 'moveSpeed', strongest: true }, merge: 'low', look: {}, icon: { emoji: '1f40c', rank: 15 } },
  speed: { name: '加速', desc: '移速乘上参数', stat: { key: 'moveSpeed' }, merge: 'high', look: { emit: { puff: 'dust', everyMs: 90, count: 2, from: 'feet' } }, icon: { emoji: '1f4a8', rank: 24 } },
  guard: { name: '减伤', desc: '受到的伤害乘上参数，小于 1 就是减伤', stat: { key: 'taken' }, merge: 'low', icon: { emoji: '1f6e1', rank: 20 } },
  dmg: { name: '增伤', desc: '造成的伤害乘上参数', stat: { key: 'damage' }, merge: 'high', icon: { emoji: '2694', rank: 23 } },
  cd: { name: '冷却', desc: '出手的冷却乘上参数，大于 1 就是出手变慢', stat: { key: 'cooldown' }, merge: 'high', icon: { emoji: '23f3', rank: 16 } },
  poison: { name: '中毒', desc: '每隔一段时间掉一次血，挨毒一层层叠上去；中了毒什么回复都不管用', cleansable: true, tint: { color: 0xc5e1a5, rank: 11.5 }, look: { emit: { puff: 'toxic', everyMs: 200, count: 2, from: 'body' } }, icon: { emoji: '1f922', rank: 13 } },
  burn: { name: '燃烧', desc: '每隔一段时间掉一次血，还会烧到贴着的同伴；水与冰浇得灭', cleansable: true, tint: { color: 0xff8a65, rank: 11 }, look: { emit: { puff: 'flame', everyMs: 80, count: 3, from: 'body' } }, icon: { emoji: '1f525', rank: 12.5 } },
  chill: { name: '寒冷', desc: '越打越慢，叠满就冻住', cleansable: true, tint: { color: 0xd6f0ff, rank: 13 }, look: { emit: { puff: 'frost', everyMs: 160, count: 2, from: 'body' } }, icon: { emoji: '1f976', rank: 15.5 } },
  wet: { name: '湿', desc: '点不着火，一冰就冻，一电一片', cleansable: true, tint: { color: 0xa9d4fb, rank: 12 }, look: { emit: { puff: 'drip', everyMs: 160, count: 2, from: 'body' } }, icon: { emoji: '1f4a7', rank: 13.5 } },
  stun: { name: '眩晕', desc: '晕过去，什么都做不了', cc: true, blocks: ALL, tint: { color: 0xff9ff3, rank: 2 }, halts: true, interrupts: true, look: { comic: 'stars' }, icon: { emoji: '1f4ab', rank: 1 } },
  hide: { name: '隐匿', desc: '敌人失去目标，只会乱走', hidden: true },
  taunt: { name: '嘲讽', desc: '只追着嘲讽它的人打', cc: true, forces: { kind: 'taunted', pace: 1, priority: 2 }, merge: 'bySource', look: {}, icon: { emoji: '1f4a2', rank: 6 } },
  invuln: { name: '无敌', desc: '带伤害的一下打不进来，持续伤害照样掉', invulnerable: true, look: { wrap: { cell: 'glow', color: 0xffd54f, alpha: 0.85, scale: 1.7, behind: true } }, icon: { emoji: '1f31f', rank: 18 } },
  morph: { name: '变形', desc: '变成小动物慢慢乱逛，什么都做不了，也碰不了人', cc: true, blocks: [...ALL, 'touch'], wander: 0.5, pinned: true, halts: true },
  morphImmune: { name: '免疫变形', desc: '刚变过形，一阵子内不会再被变形', pinned: true },
  root: { name: '定身', desc: '钉在原地走不了，仍能出手', cc: true, blocks: ['move', 'dash'], tint: { color: 0xbcaaa4, rank: 7 }, look: { shackle: 0x5d4037 }, icon: { emoji: '26d3', rank: 7 } },
  silence: { name: '沉默', desc: '放不了技能', cc: true, blocks: ['cast'], tint: { color: 0xcfd8dc, rank: 8 }, look: {}, icon: { emoji: '1f910', rank: 9 } },
  disarm: { name: '致盲', desc: '普通出手与接触都打不出去', cc: true, blocks: ['act'], tint: { color: 0x9e9e9e, rank: 9 }, look: {}, icon: { emoji: '1f648', rank: 10 } },
  ground: { name: '禁锢', desc: '不能冲刺、跳跃、闪现', cc: true, blocks: ['dash'], look: { shackle: 0x546e7a }, icon: { emoji: '2693', rank: 8 } },
  sleep: { name: '睡眠', desc: '睡着了什么都做不了；挨打即醒，叫醒的那一下伤害更高', cc: true, blocks: ALL, tint: { color: 0xb39ddb, rank: 3 }, interrupts: true, merge: 'high', look: { comic: 'zzz' }, icon: { emoji: '1f4a4', rank: 2 } },
  fear: { name: '恐惧', desc: '背离施加者逃跑', cc: true, blocks: ['act', 'cast', 'dash'], forces: { kind: 'flee', pace: 1, priority: 0 }, tint: { color: 0x9575cd, rank: 4 }, interrupts: true, merge: 'bySource', look: {}, icon: { emoji: '1f631', rank: 3 } },
  charm: { name: '魅惑', desc: '朝施加者走过去', cc: true, blocks: ['act', 'cast', 'dash'], forces: { kind: 'approach', pace: 0.75, priority: 1 }, tint: { color: 0xff80ab, rank: 5 }, interrupts: true, merge: 'bySource', look: { comic: 'hearts' }, icon: { emoji: '1f498', rank: 4 } },
  berserk: { name: '倒戈', desc: '攻击自己人', cc: true, turncoat: true, tint: { color: 0xff5252, rank: 6 }, look: {}, icon: { emoji: '1f608', rank: 5 } },
  stasis: { name: '静止', desc: '定格在原地：无敌、谁也选不中，自己也动不了', blocks: ALL, tint: { color: 0xb3e5fc, rank: 0 }, untargetable: true, untouchable: true, halts: true, interrupts: true, look: {}, icon: { emoji: '23f8', rank: 0 } },
  untargetable: { name: '不可选中', desc: '谁也选不中', untargetable: true },
  unstoppable: { name: '霸体', desc: '解除并免疫控制与被摆布，打断也不吃', steadfast: true, look: { wrap: { cell: 'glow', color: 0xff7043, alpha: 0.7, scale: 1.6, behind: true } }, icon: { emoji: '1f4aa', rank: 17 } },
  spellShield: { name: '法术盾', desc: '挡下接下来的几次命中', look: { wrap: { cell: 'bubble', color: 0xb388ff, alpha: 0.75, scale: 1.4 } }, icon: { emoji: '1f52e', rank: 21 } },
  frontGuard: { name: '正面格挡', desc: '挡下前方一定角度内来的命中', look: { guardArc: 0xbbdefb } },
  reveal: { name: '显形', desc: '隐匿与潜行在它身上失效', reveals: true, icon: { emoji: '1f441', rank: 26 } },
  undying: { name: '不灭', desc: '生命不会低于 1', icon: { emoji: '267e', rank: 19 } },
  realm: { name: '结界', desc: '和施法者一起被拉进只有彼此的异界，界外谁也插不了手' },
  parry: { name: '招架', desc: '挡下所有命中，并对出手的人还以颜色', look: { wrap: { cell: 'glow', color: 0xffffff, alpha: 0.8, scale: 1.5, behind: true } }, icon: { emoji: '1f93a', rank: 22 } },
  stealth: { name: '潜行', desc: '看不见，出手就现形', hidden: true },
  stack: { name: '叠层', desc: '叠层计数：时限内叠满就触发', keyed: true },
  fuse: { name: '引信', desc: '挂着引信，到点引爆', keyed: true, look: { emit: { puff: 'fuse', everyMs: 80, count: 3, from: 'head' } }, icon: { emoji: '1f4a3', rank: 12 } },
  store: { name: '存伤', desc: '这段时间记下受到的伤害，到时按比例结算', keyed: true },
  empower: { name: '强化', desc: '接下来几次普通出手附带额外效果', icon: { emoji: '26a1', rank: 25 } },
  deathMark: { name: '死亡印记', desc: '期间死去就触发印记的效果', keyed: true, icon: { emoji: '1f480', rank: 11 } },
  mist: { name: '墨云', desc: '在墨云里：只会被同在墨云里的出手打到' },
  devoured: { name: '被吞', desc: '被吞进肚子：动不了、谁也选不中，挨够伤害才被吐出来', blocks: ALL, untargetable: true },
  undead: { name: '亡后残留', desc: '倒下后撑着一口气：生命回来一些，随后流失殆尽，期间照常行动', tint: { color: 0x90a4ae, rank: 1 } },
  grow: { name: '成长', desc: '体型乘上参数，受击与接触范围随之变化', stat: { key: 'scale' }, merge: 'high' },
  exposed: { name: '易伤', desc: '受到的伤害乘上参数，大于 1 就是易伤', stat: { key: 'taken' }, merge: 'high', icon: { emoji: '1f3af', rank: 14 } },
  frozen: { name: '冻结', desc: '冻成一块冰，什么都做不了', cc: true, blocks: ALL, tint: { color: 0x81d4fa, rank: 10 }, halts: true, interrupts: true, look: { wrap: { cell: 'ice', color: 0xb3e5fc, alpha: 0.85, scale: 1.2 } }, icon: { emoji: '1f9ca', rank: 1.5 } },
  attuned: { name: '转属', desc: '暂时变成另一种元素：免疫的、湿不湿、出手默认带的都跟着变', look: { emit: { puff: 'element', everyMs: 160, count: 2, from: 'body' } }, icon: { emoji: '1f504', rank: 28 } },
  shield: { name: '护盾', desc: '挡下一定量的伤害，挡满了就碎', look: { wrap: { cell: 'bubble', color: 0x80cbc4, alpha: 0.75, scale: 1.4 } }, icon: { emoji: '1f4a0', rank: 19.5 } },
  mending: { name: '回春', desc: '每隔一段时间回一次血', merge: 'rate', look: { emit: { puff: 'mend', everyMs: 200, count: 2, from: 'body' } }, icon: { emoji: '1f49a', rank: 24.5 } },
  imbue: { name: '附魔', desc: '出手带上附的元素，盖过能力与自己的元素', look: { emit: { puff: 'element', everyMs: 140, count: 2, from: 'body' } }, icon: { emoji: '1fa84', rank: 27 } },
} satisfies Record<string, StatusDef>
