import type { StatDef } from '../src/types/stats'

export const STATS = {
  maxHp: { name: '生命上限', base: 0, min: 10, unit: 'count', category: 'survival', better: 'higher' },
  regen: { name: '生命回复', base: 0, min: 0, unit: 'perSec', category: 'survival', better: 'higher' },
  lifesteal: { name: '吸血', base: 0, min: 0, unit: 'percent', category: 'survival', better: 'higher' },
  armor: { name: '护甲', base: 0, unit: 'count', category: 'survival', better: 'higher' },
  dodge: { name: '闪避', base: 0, min: 0, max: 0.6, unit: 'chance', category: 'survival', better: 'higher' },
  iframes: { name: '受击无敌', base: 0, min: 0, unit: 'ms', category: 'survival', better: 'higher' },
  taken: { name: '受到伤害', base: 1, min: 0, unit: 'ratio', category: 'survival', better: 'lower' },
  blocks: { name: '每波护盾', base: 0, min: 0, unit: 'count', category: 'survival', better: 'higher' },
  thorns: { name: '近战反伤', base: 0, min: 0, unit: 'count', category: 'survival', better: 'higher' },
  killHeal: { name: '击杀回复', base: 0, min: 0, unit: 'count', category: 'survival', better: 'higher' },
  healing: { name: '治疗效果', base: 1, min: 0, unit: 'ratio', category: 'survival', better: 'higher' },
  damage: { name: '伤害', base: 1, min: 0, unit: 'ratio', category: 'offense', better: 'higher' },
  meleeDamage: { name: '近战伤害', base: 1, min: 0, unit: 'ratio', category: 'offense', better: 'higher' },
  rangedDamage: { name: '远程伤害', base: 1, min: 0, unit: 'ratio', category: 'offense', better: 'higher' },
  areaDamage: { name: '范围伤害', base: 1, min: 0, unit: 'ratio', category: 'offense', better: 'higher' },
  dotDamage: { name: '持续伤害', base: 1, min: 0, unit: 'ratio', category: 'offense', better: 'higher' },
  summonDamage: { name: '召唤物伤害', base: 1, min: 0, unit: 'ratio', category: 'offense', better: 'higher' },
  bossDamage: { name: '首领伤害', base: 1, min: 0, unit: 'ratio', category: 'offense', better: 'higher' },
  crit: { name: '暴击率', base: 0, min: 0, max: 0.5, unit: 'chance', category: 'offense', better: 'higher' },
  critDamage: { name: '暴击伤害', base: 2, min: 1, unit: 'ratio', category: 'offense', better: 'higher' },
  cooldown: { name: '攻速', base: 1, min: 0.1, unit: 'rate', category: 'offense', better: 'lower' },
  skillCooldown: { name: '技能急速', base: 1, min: 0.1, unit: 'rate', category: 'offense', better: 'lower' },
  knockback: { name: '击退', base: 1, min: 0, unit: 'ratio', category: 'offense', better: 'higher' },
  range: { name: '攻击范围', base: 1, min: 0.1, unit: 'ratio', category: 'offense', better: 'higher' },
  projSpeed: { name: '弹速', base: 1, min: 0.1, unit: 'ratio', category: 'offense', better: 'higher' },
  moveSpeed: { name: '移速', base: 0, min: 0, unit: 'gridPerSec', category: 'mobility', better: 'higher' },
  maxStamina: { name: '体力上限', base: 100, min: 1, unit: 'count', category: 'mobility', better: 'higher' },
  staminaRegen: { name: '体力回复', base: 60, min: 0, unit: 'perSec', category: 'mobility', better: 'higher' },
  exertion: { name: '赶路耗体力', base: 1, min: 0, unit: 'ratio', category: 'mobility', better: 'lower' },
  scale: { name: '体型', base: 1, min: 0.05, unit: 'ratio', category: 'mobility', better: 'neither' },
  magnet: { name: '拾取范围', base: 0, min: 0, unit: 'grid', category: 'mobility', better: 'higher' },
  harvest: { name: '每波收获', base: 0, min: 0, unit: 'count', category: 'economy', better: 'higher' },
  luck: { name: '幸运', base: 0, unit: 'count', category: 'economy', better: 'higher' },
  shopPrice: { name: '商店价格', base: 1, min: 0.1, unit: 'ratio', category: 'economy', better: 'lower' },
  freeRerolls: { name: '进店免费刷新', base: 0, min: 0, unit: 'count', category: 'economy', better: 'higher' },
  enemySpeed: { name: '敌人移速', base: 1, min: 0.1, unit: 'ratio', category: 'field', better: 'lower' },
  enemyCount: { name: '敌人数量', base: 1, min: 0.1, unit: 'ratio', category: 'field', better: 'neither' },
} as const satisfies Record<string, StatDef>
