import type { StatusDef } from '../src/types/statuses'

const ALL = ['move', 'act', 'cast', 'dash'] as const

/** 状态表：身体上带时限的标记，能封住的动作、逼着做的事、折进属性的倍率与底色都写在这里 */
export const STATUSES = {
  slow: { name: '减速', cleansable: true, stat: { key: 'moveSpeed', strongest: true } },
  speed: { name: '加速', stat: { key: 'moveSpeed' } },
  guard: { name: '减伤', stat: { key: 'taken' } },
  dmg: { name: '增伤', stat: { key: 'damage' } },
  cd: { name: '冷却', stat: { key: 'cooldown' } },
  poison: { name: '中毒' },
  stun: { name: '眩晕', cc: true, blocks: ALL, tint: { color: 0xff9ff3, rank: 2 }, halts: true, interrupts: true },
  hide: { name: '隐匿', hidden: true },
  taunt: { name: '嘲讽', cc: true, forces: { kind: 'taunted', pace: 1, priority: 2 } },
  invuln: { name: '无敌', invulnerable: true },
  morph: { name: '变形', cc: true, blocks: [...ALL, 'touch'], wander: 0.5, pinned: true, halts: true },
  morphImmune: { name: '免疫变形', pinned: true },
  root: { name: '定身', cc: true, blocks: ['move', 'dash'], tint: { color: 0xbcaaa4, rank: 7 } },
  silence: { name: '沉默', cc: true, blocks: ['cast'], tint: { color: 0xcfd8dc, rank: 8 } },
  disarm: { name: '致盲', cc: true, blocks: ['act'], tint: { color: 0x9e9e9e, rank: 9 } },
  ground: { name: '禁锢', cc: true, blocks: ['dash'] },
  sleep: { name: '睡眠', cc: true, blocks: ALL, tint: { color: 0xb39ddb, rank: 3 }, interrupts: true },
  fear: { name: '恐惧', cc: true, blocks: ['act', 'cast', 'dash'], forces: { kind: 'flee', pace: 1, priority: 0 }, tint: { color: 0x9575cd, rank: 4 }, interrupts: true },
  charm: { name: '魅惑', cc: true, blocks: ['act', 'cast', 'dash'], forces: { kind: 'approach', pace: 0.75, priority: 1 }, tint: { color: 0xff80ab, rank: 5 }, interrupts: true },
  berserk: { name: '倒戈', cc: true, turncoat: true, tint: { color: 0xff5252, rank: 6 } },
  stasis: { name: '静止', blocks: ALL, tint: { color: 0xb3e5fc, rank: 0 }, untargetable: true, untouchable: true, halts: true, interrupts: true },
  untargetable: { name: '不可选中', untargetable: true },
  unstoppable: { name: '霸体', steadfast: true },
  spellShield: { name: '法术盾' },
  frontGuard: { name: '正面格挡' },
  reveal: { name: '显形', reveals: true },
  undying: { name: '不灭' },
  realm: { name: '结界' },
  parry: { name: '招架' },
  stealth: { name: '潜行', hidden: true },
  stack: { name: '叠层', keyed: true },
  fuse: { name: '引信', keyed: true },
  store: { name: '存伤', keyed: true },
  empower: { name: '强化' },
  deathMark: { name: '死亡印记', keyed: true },
  mist: { name: '墨云' },
  devoured: { name: '被吞', blocks: ALL, untargetable: true },
  undead: { name: '亡后残留', tint: { color: 0x90a4ae, rank: 1 } },
  grow: { name: '成长', stat: { key: 'scale' } },
} satisfies Record<string, StatusDef>
