import type { StatusDef } from '../src/types/statuses'

const ALL = ['move', 'act', 'cast', 'dash'] as const

/** 状态表：身体上带时限的标记，能封住的动作、逼着做的事、折进属性的倍率、再上一次怎么并、底色与图标都写在这里 */
export const STATUSES = {
  slow: { name: '减速', cleansable: true, stat: { key: 'moveSpeed', strongest: true }, merge: 'low', icon: { emoji: '1f40c', rank: 15 } },
  speed: { name: '加速', stat: { key: 'moveSpeed' }, merge: 'high', icon: { emoji: '1f4a8', rank: 24 } },
  guard: { name: '减伤', stat: { key: 'taken' }, merge: 'low', icon: { emoji: '1f6e1', rank: 20 } },
  dmg: { name: '增伤', stat: { key: 'damage' }, merge: 'high', icon: { emoji: '2694', rank: 23 } },
  cd: { name: '冷却', stat: { key: 'cooldown' }, merge: 'high', icon: { emoji: '23f3', rank: 16 } },
  poison: { name: '中毒', merge: 'rate', icon: { emoji: '1f922', rank: 13 } },
  stun: { name: '眩晕', cc: true, blocks: ALL, tint: { color: 0xff9ff3, rank: 2 }, halts: true, interrupts: true, icon: { emoji: '1f4ab', rank: 1 } },
  hide: { name: '隐匿', hidden: true },
  taunt: { name: '嘲讽', cc: true, forces: { kind: 'taunted', pace: 1, priority: 2 }, merge: 'bySource', icon: { emoji: '1f4a2', rank: 6 } },
  invuln: { name: '无敌', invulnerable: true, icon: { emoji: '1f31f', rank: 18 } },
  morph: { name: '变形', cc: true, blocks: [...ALL, 'touch'], wander: 0.5, pinned: true, halts: true },
  morphImmune: { name: '免疫变形', pinned: true },
  root: { name: '定身', cc: true, blocks: ['move', 'dash'], tint: { color: 0xbcaaa4, rank: 7 }, icon: { emoji: '26d3', rank: 7 } },
  silence: { name: '沉默', cc: true, blocks: ['cast'], tint: { color: 0xcfd8dc, rank: 8 }, icon: { emoji: '1f910', rank: 9 } },
  disarm: { name: '致盲', cc: true, blocks: ['act'], tint: { color: 0x9e9e9e, rank: 9 }, icon: { emoji: '1f648', rank: 10 } },
  ground: { name: '禁锢', cc: true, blocks: ['dash'], icon: { emoji: '2693', rank: 8 } },
  sleep: { name: '睡眠', cc: true, blocks: ALL, tint: { color: 0xb39ddb, rank: 3 }, interrupts: true, merge: 'high', icon: { emoji: '1f4a4', rank: 2 } },
  fear: { name: '恐惧', cc: true, blocks: ['act', 'cast', 'dash'], forces: { kind: 'flee', pace: 1, priority: 0 }, tint: { color: 0x9575cd, rank: 4 }, interrupts: true, merge: 'bySource', icon: { emoji: '1f631', rank: 3 } },
  charm: { name: '魅惑', cc: true, blocks: ['act', 'cast', 'dash'], forces: { kind: 'approach', pace: 0.75, priority: 1 }, tint: { color: 0xff80ab, rank: 5 }, interrupts: true, merge: 'bySource', icon: { emoji: '1f498', rank: 4 } },
  berserk: { name: '倒戈', cc: true, turncoat: true, tint: { color: 0xff5252, rank: 6 }, icon: { emoji: '1f608', rank: 5 } },
  stasis: { name: '静止', blocks: ALL, tint: { color: 0xb3e5fc, rank: 0 }, untargetable: true, untouchable: true, halts: true, interrupts: true, icon: { emoji: '23f8', rank: 0 } },
  untargetable: { name: '不可选中', untargetable: true },
  unstoppable: { name: '霸体', steadfast: true, icon: { emoji: '1f4aa', rank: 17 } },
  spellShield: { name: '法术盾', icon: { emoji: '1f52e', rank: 21 } },
  frontGuard: { name: '正面格挡' },
  reveal: { name: '显形', reveals: true, icon: { emoji: '1f441', rank: 26 } },
  undying: { name: '不灭', icon: { emoji: '267e', rank: 19 } },
  realm: { name: '结界' },
  parry: { name: '招架', icon: { emoji: '1f93a', rank: 22 } },
  stealth: { name: '潜行', hidden: true },
  stack: { name: '叠层', keyed: true },
  fuse: { name: '引信', keyed: true, icon: { emoji: '1f4a3', rank: 12 } },
  store: { name: '存伤', keyed: true },
  empower: { name: '强化', icon: { emoji: '26a1', rank: 25 } },
  deathMark: { name: '死亡印记', keyed: true, icon: { emoji: '1f480', rank: 11 } },
  mist: { name: '墨云' },
  devoured: { name: '被吞', blocks: ALL, untargetable: true },
  undead: { name: '亡后残留', tint: { color: 0x90a4ae, rank: 1 } },
  grow: { name: '成长', stat: { key: 'scale' }, merge: 'high' },
  exposed: { name: '易伤', stat: { key: 'taken' }, merge: 'high', icon: { emoji: '1f3af', rank: 14 } },
} satisfies Record<string, StatusDef>
