import type { EnemyDef } from '../../../../legacy/types/enemies'
import { shot } from '../../../kit.ts'

const LEECH = [{ kind: 'to', who: { side: 'self' }, then: [{ kind: 'healRatio', ratio: 0.02 }] }] as const

const VAMPIRE_COUNT = {
  kind: 'vampireCount',
  role: 'boss',
  emoji: '1f9db',
  name: '吸血伯爵',
  element: 'ice',
  desc: '住在晶洞深处的冷血伯爵，本身是冰，冻不住：一挥手洒出三发冷血弹，打中的叠一层寒冷，贴得越近挨得越多；扑上来咬一口，吸回自己 2% 的生命，冻住的人被这一口咬得碎冰、伤害翻倍；咬之前要蓄力 0.4 秒，挨一下雷就咬不下去；隔一阵把 6 格内最近的人拖进暗影界单挑 5 秒，界外的人插不了手；隔一阵化作一只大蝙蝠，4 秒里飞得又高又快，俯冲着吸血；中了毒就吸不回血；血掉到四成迎来血月，伤害 ×1.25，霸体 2 秒',
  size: 3.3,
  radius: 1.1,
  span: [0, 6],
  hp: 3900,
  stats: { armor: 4, exertion: 0 },
  speed: 1.3,
  damage: 18,
  xp: 40,
  coins: 40,
  traits: ['anchored', 'wary'],
  drive: { kind: 'chase' },
  abilities: [
    {
      trigger: 'auto',
      cooldownMs: 2200,
      firstDelayMs: 900,
      aim: 'nearest',
      range: 2.2,
      element: 'physical',
      damage: 22,
      knockback: 1,
      fireSfx: 'gulp',
      windup: { ms: 400, lockAt: 'end', telegraph: 'shake' },
      shape: { kind: 'segment', reach: 1.8, radius: 0.6, ms: 180 },
      onHit: LEECH,
    },
    {
      trigger: 'auto',
      cooldownMs: 3200,
      firstDelayMs: 1800,
      aim: 'nearest',
      range: 8,
      damage: 11,
      fireSfx: 'shoot',
      color: 0x80deea,
      shape: { kind: 'bolt', projectile: shot('1fa78', 6.5, 0.5), lifeMs: 1800 },
      repeat: { count: 3, spreadDeg: 30 },
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 16000,
      firstDelayMs: 10000,
      aim: 'nearest',
      range: 6,
      fireSfx: 'warp',
      color: 0x4a148c,
      shape: { kind: 'disc', radius: 0.8, at: 'target' },
      onHit: [{ kind: 'realm', ms: 5000 }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 13000,
      firstDelayMs: 7000,
      aim: 'self',
      fireSfx: 'flutter',
      shape: { kind: 'world' },
      reactions: [{ on: 'fire', to: 'self', effects: [{ kind: 'form', to: 0, ms: 4000 }] }],
    },
  ],
  forms: [
    {
      emoji: '1f987',
      name: '蝠形',
      span: [2, 3],
      stats: { mul: { moveSpeed: 1.8 } },
      abilities: [
        {
          trigger: 'auto',
          cooldownMs: 1300,
          firstDelayMs: 300,
          aim: 'nearest',
          range: 4.5,
          element: 'physical',
          damage: 16,
          knockback: 2,
          fireSfx: 'whoosh',
          shape: { kind: 'sprint', distance: 4, ms: 360, radius: 1.5 },
          onHit: LEECH,
        },
      ],
    },
  ],
  phases: [{ below: 0.4, name: '血月', stats: { mul: { damage: 1.25 } }, effects: [{ kind: 'unstoppable', durationMs: 2000 }] }],
} satisfies EnemyDef

export default VAMPIRE_COUNT
