import type { EnemyDef } from '../../../src/types/enemies'

const DESERT_BOSS = {
  kind: 'scorpion',
  role: 'boss',
  emoji: '1f982',
  name: '蝎王',
  desc: '遁入沙中不可选中地疾行，破土时掀飞周围的人；召出把人往中心卷的流沙漩涡，越挣扎越累；毒针叠满四层就抽空体力；尾刺猛扑，击退免疫',
  size: 3.2,
  radius: 1.05,
  span: [0, 6],
  hp: 4500,
  stats: { armor: 5, exertion: 0 },
  speed: 1.5,
  damage: 22,
  xp: 60,
  coins: 60,
  traits: ['anchored', 'wary'],
  drive: { kind: 'chase', at: 'leader' },
  abilities: [
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 6000,
      firstDelayMs: 3500,
      aim: 'leader',
      windup: { ms: 650, lockAt: 'end', telegraph: 'shake' },
      fireSfx: 'whoosh',
      shape: { kind: 'sprint', distance: 5.5, ms: 500 },
    },
    {
      trigger: 'auto',
      cooldownMs: 3000,
      firstDelayMs: 1800,
      aim: 'nearest',
      damage: 8,
      shape: { kind: 'bolt', projectile: { look: { emoji: '1f7e3', size: 0.42, rotationOffsetDeg: 0 }, radius: 0.15, speed: 3.2 }, lifeMs: 5000 },
      repeat: { count: 5, spreadDeg: 70 },
      onHit: [{ kind: 'stack', max: 4, durationMs: 5000, then: [{ kind: 'exhaust' }] }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 9000,
      firstDelayMs: 5000,
      aim: 'self',
      fireSfx: 'whoosh',
      shape: { kind: 'world' },
      reactions: [{ on: 'fire', to: 'self', effects: [
        { kind: 'untargetable', durationMs: 1800 },
        { kind: 'buff', speedMul: 2.2, durationMs: 1800 },
        { kind: 'fuse', ms: 1800, then: [{ kind: 'to', who: { side: 'foes', radius: 2.6 }, then: [{ kind: 'knockup', durationMs: 800, height: 1.4 }, { kind: 'damage', amount: 16 }] }] },
      ] }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 12000,
      firstDelayMs: 7000,
      aim: 'nearest',
      range: 12,
      fireSfx: 'boom',
      shape: { kind: 'disc', radius: 1, at: 'target' },
      onHit: [{ kind: 'ground', def: { radius: 4.5, durationMs: 5000, tickMs: 500, damage: 4, color: 0xd7ccc8, fillAlpha: 0.25, lineAlpha: 0.6, enterMs: 400, pull: 1.6, exertion: 5 } }],
    },
  ],
} satisfies EnemyDef

export default DESERT_BOSS
