import { hslToInt } from '../../../src/util/palette.ts'
import type { MapDef } from '../../../src/types/maps'

export default {
  emoji: '2744',
  name: '浮冰',
  desc: '南极海上漂着的一块浮冰，四面都是冰点上下的海水。积雪的地方踩得住，裸露的老冰和裂缝冻成的新冰滑得站不稳——走不跟手、刹不住，挨一下能滑出老远；滑出冰缘就掉进海里，冷水几秒就把人冻僵（敌我通吃）。海风一阵阵刮过来，阵风大时新冰上站不住，个子小的在光冰上也会被吹着滑',
  kind: 'floe',
  stamina: { exertion: 0.3, regen: 0.9 },
  palette: {
    bgFrom: 'hsl(202 38% 24%)',
    bgTo: 'hsl(214 48% 7%)',
    map: hslToInt(200, 0.22, 0.86),
  },
  light: { sun: 0xffffff, shade: 0xc4d2e0, shadow: { color: 0x1a3a66, alpha: 0.38, length: 1.5 } },
  decor: {
    emojis: ['2744', '1f9ca'],
    sizeU: [0.3, 0.7],
    alpha: [0.14, 0.28],
    density: [0.05, 0.09],
  },
  foes: ['zombie', 'boar', 'ghost', 'blob', 'snake', 'turtle', 'creeper', 'crab', 'knight'],
  gates: {
    snapU: 4,
    fallback: 'rise',
    look: 'snow',
    boss: 'sky',
    lean: { mul: 3, full: 13 },
    kinds: {
      edge: { name: '冰缘', at: { kind: 'rim', segU: 3 }, enter: 'climb', look: 'splash', snapU: 8, weight: 3, perSec: 1.5, only: ['zombie', 'turtle', 'crab', 'snake', 'blob'] },
      seam: { name: '新冰缝', at: { kind: 'mark' }, enter: 'rise', look: 'splash', weight: 2, perSec: 1, only: ['turtle', 'crab', 'snake'] },
      drift: { name: '雪堆', at: { kind: 'mark' }, enter: 'rise', look: 'snow', weight: 2, perSec: 1.5, only: ['zombie', 'boar', 'blob', 'creeper', 'knight'] },
      squall: { name: '风雪', at: { kind: 'ground' }, enter: 'drop', look: 'snow', weight: 1.5, only: ['ghost'] },
      sky: { name: '天上', at: { kind: 'ground' }, enter: 'drop', look: 'snow', weight: 1, only: ['swan'] },
    },
  },
  floe: {
    meterPerU: 0.4,
    cellU: 0.125,
    shape: {
      spanU: 32,
      turnDeg: 8,
      sideDeg: 6,
      sideU: 1.5,
      cutChance: 0.55,
      cutU: [1.5, 5],
      bendU: 0.9,
      bites: [1, 2],
      biteDepthU: [2.5, 5],
      biteWidthU: [4, 8],
      leadChance: 0.6,
      leadU: [5, 9],
      leadWidthU: [1.2, 1.9],
      seamWidthU: [0.9, 1.6],
      jagU: 0.22,
      roundU: [0.8, 2.2],
    },
    ice: { thicknessM: 1.6, youngM: 0.25, density: 917, seaDensity: 1027 },
    snow: { maxM: 0.18, cover: 0.5, density: 330, waveU: 3.5, bareU: 1.6 },
    friction: { snow: { static: 0.55, kinetic: 0.42 }, ice: { static: 0.22, kinetic: 0.16 }, young: { static: 0.11, kinetic: 0.07 }, loose: 0.12 },
    body: { footFrac: 0.6, swimRatio: 0.3, refRadiusU: 0.45, dragU: 1, freezeSec: 8, climbFrac: 0.5 },
    wind: {
      meanMs: 7,
      gustMs: 13,
      firstMs: 20000,
      intervalMs: 36000,
      jitterMs: 8000,
      riseMs: 2500,
      holdMs: 3500,
      fallMs: 3000,
      veerDeg: 15,
      airDensity: 1.34,
      dragArea: 0.012,
      driftRatio: 0.02,
      driftDeg: 30,
      fetchM: 150,
    },
    waterExertion: 1.5,
    waterRegen: 0.2,
    coldTickMs: 250,
  },
  boss: 'swan',
} as const satisfies MapDef
