import type { EnemyDef } from '../../../../src/types/enemies'

const BEAR = {
  kind: 'bear',
  role: 'boss',
  emoji: '1f43b',
  name: '林中熊',
  element: 'earth',
  desc: '林子里的大熊：熊掌一扇扫开一片，一声咆哮吓跑身边的人，隔一阵低头冲撞；血掉到一半就暴怒，越打越快',
  size: 3.2,
  radius: 1.05,
  span: [0, 6],
  hp: 2400,
  stats: { armor: 5, exertion: 0 },
  speed: 1.25,
  damage: 16,
  xp: 40,
  coins: 40,
  traits: ['anchored', 'wary'],
  drive: { kind: 'chase' },
  abilities: [
    {
      trigger: 'auto',
      cooldownMs: 1700,
      firstDelayMs: 800,
      aim: 'nearest',
      range: 2.8,
      damage: 22,
      knockback: 3,
      fireSfx: 'whoosh',
      windup: { ms: 450, lockAt: 'end', telegraph: 'shake' },
      shape: { kind: 'sector', radius: 2.8, arcDeg: 120, ms: 200 },
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 10000,
      firstDelayMs: 5000,
      aim: 'self',
      fireSfx: 'rumble',
      color: 0x8d6e63,
      windup: { ms: 700, lockAt: 'start', telegraph: 'shake' },
      shape: { kind: 'disc', radius: 4.2, at: 'self' },
      onHit: [{ kind: 'fear', durationMs: 1300 }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 7000,
      firstDelayMs: 3000,
      aim: 'nearest',
      range: 7,
      damage: 28,
      knockback: 6,
      fireSfx: 'charge',
      windup: { ms: 800, lockAt: 'start', telegraph: 'shake' },
      shape: { kind: 'sprint', distance: 7, ms: 700 },
    },
  ],
  phases: [{ below: 0.5, name: '暴怒', stats: { mul: { moveSpeed: 1.3, damage: 1.2, cooldown: 0.8 } }, effects: [{ kind: 'unstoppable', durationMs: 2500 }] }],
} satisfies EnemyDef

export default BEAR
