import type { EnemyDef } from '../../../../legacy/types/enemies'

const BEAR = {
  kind: 'bear',
  role: 'boss',
  emoji: '1f43b',
  name: '林中熊',
  desc: '林子里的大熊，皮糙肉厚，刀砍的打折扣，火烧毒蚀照单全收；每秒回 6 点血，中了毒就回不了：熊掌一扇扫开一片，一声咆哮吓跑身边的人，隔一阵低头冲撞，撞中的被顶出 4 格，撞上林缘、栅栏或坡脚的晕 1 秒；血掉到一半就暴怒，越打越快，近身打它的每下挨 10 点反伤',
  size: 3.2,
  radius: 1.05,
  span: [0, 6],
  hp: 2000,
  stats: { armor: 8, regen: 6, exertion: 0 },
  speed: 1.25,
  damage: 16,
  xp: 40,
  coins: 40,
  traits: ['anchored', 'wary'],
  drive: { kind: 'chase' },
  abilities: [
    {
      trigger: 'auto',
      cooldownMs: 1700,
      firstDelayMs: 800,
      aim: 'nearest',
      range: 2.8,
      damage: 22,
      knockback: 3,
      fireSfx: 'whoosh',
      windup: { ms: 450, lockAt: 'end', telegraph: 'shake' },
      shape: { kind: 'sector', radius: 2.8, arcDeg: 120, ms: 200 },
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 10000,
      firstDelayMs: 5000,
      aim: 'self',
      fireSfx: 'rumble',
      color: 0x8d6e63,
      windup: { ms: 700, lockAt: 'start', telegraph: 'shake' },
      shape: { kind: 'disc', radius: 4.2, at: 'self' },
      onHit: [{ kind: 'fear', durationMs: 1300 }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 7000,
      firstDelayMs: 3000,
      aim: 'nearest',
      range: 7,
      damage: 28,
      fireSfx: 'charge',
      windup: { ms: 800, lockAt: 'start', telegraph: 'shake' },
      shape: { kind: 'sprint', distance: 7, ms: 700, radius: 1.5 },
      onHit: [{ kind: 'shove', distance: 4, ms: 380, onWall: [{ kind: 'stun', durationMs: 1000 }] }],
    },
  ],
  phases: [{ below: 0.5, name: '暴怒', stats: { add: { thorns: 10 }, mul: { moveSpeed: 1.3, damage: 1.2, cooldown: 0.8 } }, effects: [{ kind: 'unstoppable', durationMs: 2500 }] }],
} satisfies EnemyDef

export default BEAR
