export enum SceneKey {
  Preload = 'preload',
  Menu = 'menu',
  Map = 'map',
  Wiki = 'wiki',
  Studio = 'studio',
  Editor = 'editor',
  Settings = 'settings',
  Recruit = 'recruit',
  Shop = 'shop',
  Battle = 'battle',
  Ui = 'ui',
  DevTools = 'devtools',
  Result = 'result',
  Pause = 'pause',
  LevelUp = 'levelUp',
  LevelUpRecruit = 'levelUpRecruit',
}
