import type { EnemyDef } from '../../../src/types/enemies'

const SPACE_BOSS = {
  kind: 'blackhole',
  role: 'boss',
  emoji: '1f573',
  name: '视界之主',
  desc: '张开事件视界，越过那道圈的人（进出都算）当场被定住；引力换位把一名队员和自己对调；吸积盘环爆与坍缩坠击，击退免疫',
  size: 3.4,
  radius: 1.1,
  span: [0, 6],
  hp: 6600,
  stats: { exertion: 0 },
  speed: 1.15,
  damage: 20,
  xp: 60,
  coins: 60,
  traits: ['anchored', 'wary'],
  drive: { kind: 'chase' },
  abilities: [
    {
      trigger: 'auto',
      cooldownMs: 2800,
      firstDelayMs: 1600,
      aim: 'nearest',
      damage: 8,
      shape: { kind: 'bolt', projectile: { look: { emoji: '1f7e3', size: 0.5, rotationOffsetDeg: 0 }, radius: 0.18, speed: 2.5 }, lifeMs: 5000 },
      repeat: { count: 16, spreadDeg: 360 },
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 14000,
      firstDelayMs: 3000,
      aim: 'self',
      fireSfx: 'zap',
      shape: { kind: 'world' },
      onHit: [
        {
          kind: 'barrier',
          shape: 'ring',
          length: 4.5,
          durationMs: 6000,
          bodies: 'none',
          shots: false,
          follow: true,
          onCross: [{ kind: 'stun', durationMs: 1500 }, { kind: 'damage', amount: 15 }],
          color: 0x7e57c2,
        },
      ],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 9000,
      firstDelayMs: 6000,
      aim: 'nearest',
      range: 10,
      windup: { ms: 600, lockAt: 'end', telegraph: 'blink' },
      fireSfx: 'whoosh',
      color: 0xb388ff,
      shape: { kind: 'segment', reach: 10, radius: 0.5, ms: 0, beam: true },
      onHit: [{ kind: 'swap' }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 4600,
      aim: 'nearest',
      damage: 22,
      shape: { kind: 'drop', targets: 4, look: { emoji: '1f311', size: 1.0 }, fromAbove: 4, dropMs: 240, staggerMs: 80 },
    },
  ],
} satisfies EnemyDef

export default SPACE_BOSS
