import type { EnemyDef } from '../../../src/types/enemies'

const RIVER_BOSS = {
  kind: 'croc',
  role: 'boss',
  emoji: '1f40a',
  name: '巨鳄',
  desc: '一口吞下贴近的队员慢慢消化，打它够疼才吐出来；死亡翻滚时霸体横扫；水弹扇幕与浪头拍击，击退免疫',
  size: 3.4,
  radius: 1.1,
  span: [0, 6],
  hp: 4040,
  stats: { armor: 8, exertion: 0 },
  speed: 1.3,
  damage: 20,
  xp: 60,
  coins: 60,
  traits: ['anchored', 'wary'],
  drive: { kind: 'chase' },
  abilities: [
    {
      trigger: 'auto',
      cooldownMs: 3200,
      firstDelayMs: 1800,
      aim: 'nearest',
      damage: 9,
      shape: { kind: 'bolt', projectile: { look: { emoji: '1f535', size: 0.5, rotationOffsetDeg: 0 }, radius: 0.18, speed: 2.6 }, lifeMs: 5000 },
      repeat: { count: 6, spreadDeg: 90 },
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 10000,
      firstDelayMs: 5000,
      aim: 'nearest',
      range: 3,
      windup: { ms: 700, lockAt: 'end', telegraph: 'blink' },
      fireSfx: 'boom',
      shape: { kind: 'segment', reach: 2.6, radius: 0.8, ms: 200 },
      onHit: [{ kind: 'devour', ms: 4000, dps: 12, escape: 260, spit: 3 }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 12000,
      firstDelayMs: 8000,
      aim: 'nearest',
      fireSfx: 'whoosh',
      damage: 14,
      knockback: 12,
      shape: { kind: 'sector', radius: 2.8, arcDeg: 360, ms: 300 },
      repeat: { count: 4, delayMs: 300 },
      reactions: [{ on: 'fire', to: 'self', effects: [{ kind: 'unstoppable', durationMs: 1300 }] }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 5000,
      aim: 'nearest',
      damage: 22,
      shape: { kind: 'drop', targets: 4, look: { emoji: '1f30a', size: 1.0 }, fromAbove: 4, dropMs: 240, staggerMs: 80 },
    },
  ],
} satisfies EnemyDef

export default RIVER_BOSS
