import type { EnemyDef } from '../../../src/types/enemies'

const DAYNIGHT_BOSS = {
  kind: 'eclipse',
  role: 'boss',
  emoji: '1f9db',
  name: '夜伯爵',
  desc: '把最近的队员拖进暗影界单挑五秒，界外的人插不了手；隔一阵入夜散成蝙蝠群，暗夜里一圈圈恐惧；血珠环爆与月华坠，击退免疫',
  size: 3.4,
  radius: 1.1,
  span: [0, 6],
  hp: 6300,
  stats: { exertion: 0 },
  speed: 1.25,
  damage: 20,
  xp: 60,
  coins: 60,
  traits: ['anchored', 'wary'],
  drive: { kind: 'chase' },
  abilities: [
    {
      trigger: 'auto',
      cooldownMs: 3000,
      firstDelayMs: 1600,
      aim: 'nearest',
      damage: 8,
      shape: { kind: 'bolt', projectile: { look: { emoji: '1fa78', size: 0.5, rotationOffsetDeg: 0 }, radius: 0.18, speed: 2.5 }, lifeMs: 5000 },
      repeat: { count: 14, spreadDeg: 360 },
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 16000,
      firstDelayMs: 6000,
      aim: 'nearest',
      range: 6,
      fireSfx: 'zap',
      color: 0x4a148c,
      shape: { kind: 'disc', radius: 0.8, at: 'target' },
      onHit: [{ kind: 'realm', ms: 5000 }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 18000,
      firstDelayMs: 12000,
      aim: 'self',
      fireSfx: 'boom',
      shape: { kind: 'world' },
      reactions: [{ on: 'fire', to: 'self', effects: [{ kind: 'form', to: 0, ms: 7000 }] }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 4600,
      aim: 'nearest',
      damage: 22,
      shape: { kind: 'drop', targets: 4, look: { emoji: '1f319', size: 1.0 }, fromAbove: 4, dropMs: 240, staggerMs: 80 },
    },
  ],
  forms: [
    {
      emoji: '1f987',
      name: '蝙蝠群',
      span: [1, 3],
      stats: { add: { dodge: 0.3 }, mul: { moveSpeed: 1.3 } },
      abilities: [
        {
          trigger: 'auto',
          class: 'skill',
          cooldownMs: 2600,
          firstDelayMs: 400,
          aim: 'self',
          fireSfx: 'boom',
          damage: 10,
          color: 0x311b92,
          shape: { kind: 'disc', radius: 3.5, at: 'self' },
          onHit: [{ kind: 'fear', durationMs: 1200 }],
        },
        {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 4600,
      aim: 'nearest',
      damage: 22,
      shape: { kind: 'drop', targets: 4, look: { emoji: '1f319', size: 1.0 }, fromAbove: 4, dropMs: 240, staggerMs: 80 },
    },
      ],
    },
  ],
} satisfies EnemyDef

export default DAYNIGHT_BOSS
