import type { EnemyDef } from '../../../src/types/enemies'
import PYLON from './pylon.ts'

const FACTORY_BOSS = {
  kind: 'mecha',
  role: 'boss',
  emoji: '2622',
  name: '核能机甲',
  desc: '立起护盾塔，塔还立着核心就打不动；追踪导弹紧咬不放；血过半开始泄漏、再立两座塔，环扫激光与重锤齐下；击退免疫',
  size: 3.4,
  radius: 1.1,
  span: [0, 6],
  hp: 4875,
  stats: { armor: 5, exertion: 0 },
  speed: 1.2,
  damage: 20,
  xp: 60,
  coins: 60,
  traits: ['anchored', 'wary'],
  guardedBy: 'pylon',
  drive: { kind: 'chase' },
  abilities: [
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 20000,
      firstDelayMs: 800,
      aim: 'self',
      fireSfx: 'recruit',
      shape: { kind: 'world' },
      onHit: [{ kind: 'summon', of: { unit: PYLON, spread: 5 }, count: 3 }],
    },
    {
      trigger: 'auto',
      cooldownMs: 3200,
      firstDelayMs: 2000,
      aim: 'nearest',
      damage: 9,
      fireSfx: 'shoot',
      shape: { kind: 'bolt', projectile: { look: { emoji: '1f680', size: 0.5, rotationOffsetDeg: 45 }, radius: 0.17, speed: 4.2, flight: { kind: 'homing', degPerSec: 110 } }, lifeMs: 4500 },
      repeat: { count: 4, spreadDeg: 120 },
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 4800,
      aim: 'nearest',
      damage: 24,
      shape: { kind: 'drop', targets: 5, look: { emoji: '1f528', size: 1.1 }, fromAbove: 4, dropMs: 220, staggerMs: 80 },
    },
  ],
  phases: [{ below: 0.5, name: '泄漏', effects: [{ kind: 'form', to: 0 }, { kind: 'summon', of: { unit: PYLON, spread: 5 }, count: 2 }] }],
  forms: [
    {
      emoji: '2623',
      name: '泄漏核心',
      stats: { mul: { moveSpeed: 1.4 } },
      abilities: [
        {
          trigger: 'auto',
          class: 'skill',
          cooldownMs: 2600,
          firstDelayMs: 600,
          aim: 'nearest',
          range: 8,
          damage: 8,
          fireSfx: 'zap',
          color: 0xff5252,
          shape: { kind: 'segment', reach: 8, radius: 0.3, ms: 0, beam: true },
          repeat: { count: 8, spreadDeg: 360, delayMs: 70 },
        },
        {
      trigger: 'auto',
      cooldownMs: 3200,
      firstDelayMs: 2000,
      aim: 'nearest',
      damage: 9,
      fireSfx: 'shoot',
      shape: { kind: 'bolt', projectile: { look: { emoji: '1f680', size: 0.5, rotationOffsetDeg: 45 }, radius: 0.17, speed: 4.2, flight: { kind: 'homing', degPerSec: 110 } }, lifeMs: 4500 },
      repeat: { count: 4, spreadDeg: 120 },
    },
        {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 4800,
      aim: 'nearest',
      damage: 24,
      shape: { kind: 'drop', targets: 5, look: { emoji: '1f528', size: 1.1 }, fromAbove: 4, dropMs: 220, staggerMs: 80 },
    },
      ],
    },
  ],
} satisfies EnemyDef

export default FACTORY_BOSS
