import type { EnemyDef } from '../../../src/types/enemies'

const RUINS_BOSS = {
  kind: 'rhino',
  role: 'boss',
  emoji: '1f996',
  name: '霸王龙',
  desc: '残垣头目：锁定最近的队员霸体冲锋，一路碾碎断壁、追着人拐弯，撞上就把人撞飞，撞到墙上的被砸晕；跺地震得周围的人两秒半内冲不动也闪不走；落石无视遮挡；击退免疫',
  size: 3.2,
  radius: 1.05,
  span: [0, 6],
  hp: 3910,
  stats: { armor: 8, exertion: 0 },
  speed: 1.4,
  damage: 20,
  xp: 60,
  coins: 60,
  traits: ['anchored', 'wary'],
  drive: { kind: 'chase', at: 'leader' },
  abilities: [
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 6000,
      firstDelayMs: 3200,
      aim: 'nearest',
      range: 10,
      windup: { ms: 700, lockAt: 'end', telegraph: 'shake' },
      fireSfx: 'whoosh',
      damage: 18,
      shape: { kind: 'sprint', distance: 9, ms: 1100, radius: 1.1, seek: true },
      breach: 2.4,
      reactions: [{ on: 'fire', to: 'self', effects: [{ kind: 'unstoppable', durationMs: 1200 }] }],
      onHit: [{ kind: 'shove', distance: 3, ms: 280, onWall: [{ kind: 'stun', durationMs: 1500 }, { kind: 'damage', amount: 12 }] }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 8000,
      firstDelayMs: 5000,
      aim: 'nearest',
      range: 3.2,
      windup: { ms: 800, lockAt: 'start', telegraph: 'blink' },
      fireSfx: 'boom',
      damage: 16,
      color: 0x8d6e63,
      shape: { kind: 'disc', radius: 3.4, at: 'self' },
      onHit: [{ kind: 'grounded', durationMs: 2500 }, { kind: 'slow', factor: 0.5, durationMs: 1500 }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 4500,
      aim: 'nearest',
      damage: 24,
      shape: { kind: 'drop', targets: 5, look: { emoji: '1faa8', size: 1.1 }, fromAbove: 4, dropMs: 240, staggerMs: 90 },
    },
  ],
} satisfies EnemyDef

export default RUINS_BOSS
