import type { EnemyDef } from '../../../src/types/enemies'

const ICE_BOSS = {
  kind: 'swan',
  role: 'boss',
  emoji: '1f426_200d_2b1b',
  name: '霜鸦',
  desc: '浮冰头目：扇出减速的冰晶；把一片队员冻进冰里两秒（冻住的打不了也挨不了打）；冰晶砸落铺开打滑的冰面；生命归零时缩进冰蛋，六秒内打不碎就满血复生',
  size: 3.3,
  radius: 1.05,
  span: [0, 6],
  hp: 5040,
  stats: { dodge: 0.1, exertion: 0 },
  speed: 1.35,
  damage: 20,
  xp: 60,
  coins: 60,
  traits: ['anchored', 'wary'],
  drive: { kind: 'chase' },
  abilities: [
    {
      trigger: 'auto',
      cooldownMs: 2600,
      firstDelayMs: 1500,
      aim: 'nearest',
      damage: 8,
      shape: { kind: 'bolt', projectile: { look: { emoji: '1f4a0', size: 0.5, rotationOffsetDeg: 0 }, radius: 0.17, speed: 3.5 }, lifeMs: 4500 },
      repeat: { count: 7, spreadDeg: 100 },
      onHit: [{ kind: 'slow', factor: 0.6, durationMs: 1500 }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 12000,
      firstDelayMs: 5000,
      aim: 'nearest',
      range: 9,
      windup: { ms: 700, lockAt: 'end', telegraph: 'blink' },
      fireSfx: 'zap',
      color: 0xb3e5fc,
      shape: { kind: 'disc', radius: 2.6, at: 'target' },
      onHit: [{ kind: 'stasis', durationMs: 2000 }],
    },
    {
      trigger: 'auto',
      class: 'skill',
      cooldownMs: 7000,
      firstDelayMs: 3000,
      aim: 'nearest',
      damage: 20,
      shape: { kind: 'drop', targets: 3, look: { emoji: '1f537', size: 1 }, fromAbove: 4, dropMs: 240, staggerMs: 90 },
      onHit: [{ kind: 'ground', def: { radius: 1.8, durationMs: 5000, tickMs: 0, damage: 0, color: 0xb3e5fc, fillAlpha: 0.3, lineAlpha: 0.6, enterMs: 150, traction: 0.15 } }],
    },
  ],
  reactions: [{ on: 'lethal', to: 'self', effects: [{ kind: 'healRatio', ratio: 0.2 }, { kind: 'form', to: 0, ms: 6000, onEnd: [{ kind: 'healRatio', ratio: 1 }] }] }],
  forms: [{ emoji: '1f95a', name: '冰蛋', span: [0, 3], stats: { mul: { scale: 0.7, moveSpeed: 0, dodge: 0 } }, drive: { kind: 'stay' }, abilities: [], damage: 0 }],
} satisfies EnemyDef

export default ICE_BOSS
