import { hslToInt } from '../../../src/util/palette.ts'
import type { MapDef } from '../../../src/types/maps'

export default {
  emoji: '1f30b',
  name: '火山',
  desc: '四周崖壁环绕的盆地，一座积雪的活火山背靠盆地边，陡峭的山体谁也上不去，火山周围一大片常年飘雪。它隔两分半钟上下喷发一次：先地动山摇、火山口透出红光，随后熔岩喷涌着漫过火山口，往四面八方顺着地势流下来，把雪烧化。熔岩盖住的地方敌我都受伤；离火山口越远凉得越快，凝成黑色的岩石后又能站人，雪再慢慢把岩石盖住',
  kind: 'volcano',
  size: { w: 32, h: 32 },
  stamina: { exertion: 0.5, regen: 0.9 },
  palette: {
    bgFrom: 'hsl(210 6% 19%)',
    bgTo: 'hsl(210 20% 6%)',
    map: hslToInt(209, 0.05, 0.3),
  },
  light: { sun: 0xf6ebe4, shade: 0xa29793, shadow: { color: 0x080404, alpha: 0.45, length: 0.85 } },
  decor: {
    emojis: ['1faa8', '1f9b4', '1f480'],
    sizeU: [0.3, 0.8],
    alpha: [0.2, 0.34],
    density: [0.03, 0.05],
  },
  foes: ['imp', 'bison', 'chili', 'meltling', 'steamer', 'fireMeteor', 'lavaGiant', 'quaker'],
  // 崖脚的洞里走出来、崖顶跳下来、喷气孔里钻出来、喷发时火山口抛出来、骷髅从灰里爬起来；炎魔与不死鸟从山坡上下来
  gates: {
    snapU: 3,
    fallback: 'rise',
    boss: 'foot',
    kinds: {
      cave: { name: '洞穴', at: { kind: 'nooks', spacingU: 6, away: { mark: 'cone', minU: 9 } }, enter: 'walk', snapU: 5, weight: 3, perSec: 1.5, only: ['zombie', 'boar', 'creeper', 'skeleton', 'imp', 'bison', 'chili', 'lavaGiant', 'quaker'] },
      cliff: { name: '崖顶', at: { kind: 'rim', segU: 3, away: { mark: 'cone', minU: 9 } }, enter: 'climb', snapU: 5, weight: 1.5, perSec: 1, only: ['gargoyle', 'zombie', 'bison', 'quaker'] },
      vent: { name: '喷气孔', at: { kind: 'mark' }, enter: 'rise', look: 'steam', weight: 2, perSec: 1, only: ['turtle', 'creeper', 'chili', 'meltling', 'steamer'] },
      crater: { name: '火山口', at: { kind: 'mark' }, enter: 'lob', look: 'sparks', weight: 4, perSec: 4, reachU: 14, only: ['comet', 'turtle', 'fireMeteor'] },
      ash: { name: '灰地', at: { kind: 'ground' }, enter: 'rise', weight: 1 },
      foot: { name: '山坡', at: { kind: 'mark' }, enter: 'walk', weight: 1, only: ['rhino', 'demonLord', 'phoenix'] },
    },
  },
  volcano: {
    cellU: 0.5,
    rim: { insetU: [0.5, 2.5], waveU: 7, cornerU: 5, neckU: 1, cliffU: 1.1, cliffHeight: 2.6, backSlope: 0.12 },
    cone: { insetU: [0.5, 1.5], craterU: 1.6, blockU: 4, blockJitter: 0.1, height: 4, footHeight: 0.9, radiusU: 9, craterDepth: 1.4, gullyDepth: 0.45 },
    terrain: { tilt: 0.2, relief: 1.2, waveU: 7 },
    eruption: {
      firstMs: 30000,
      intervalMs: 150000,
      intervalJitterMs: 50000,
      warnMs: 10000,
      rate: 10,
      peakMs: 1200,
      waneMs: 8000,
      effuseMs: 30000,
      lobes: [8, 12],
      lobeJitter: 0.3,
      lobeDeg: 16,
      lobeFloor: 0.08,
      history: 2,
    },
    lava: {
      stepMs: 100,
      mobility: 40,
      mobilityPow: 2,
      yieldHot: 0.015,
      yieldCold: 0.1,
      cooling: 0.012,
      coolRadiusU: 6,
      solidus: 0.3,
      teamDps: 30,
      enemyDps: 45,
      tickMs: 250,
    },
    snow: { radiusU: 17, edgeU: 6.5, wobble: 0.2, shiftU: 2, warmMs: 8000, coverMs: 40000, buryMs: 45000 },
  },
  bosses: ['demonLord', 'phoenix'],
} as const satisfies MapDef
